package view;

/**
 * Clean, detailed, and beautiful Billing & Invoicing UI matching the reference design.
 * Designed using NetBeans GUI Builder format under package view.
 *
 * @author i3
 */
public class Billing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Billing.class.getName());

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        jPanelInvoiceContainer = new javax.swing.JPanel();
        jPanelInvoiceCard = new javax.swing.JPanel();
        lblGuestIdTitle = new javax.swing.JLabel();
        lblGuestIdValue = new javax.swing.JLabel();
        lblRoomIdTitle = new javax.swing.JLabel();
        lblRoomIdValue = new javax.swing.JLabel();
        lblStayPeriodTitle = new javax.swing.JLabel();
        lblStayPeriodValue = new javax.swing.JLabel();
        jSeparatorInvoice = new javax.swing.JSeparator();
        lblColDesc = new javax.swing.JLabel();
        lblColQty = new javax.swing.JLabel();
        lblColPrice = new javax.swing.JLabel();
        lblColAmount = new javax.swing.JLabel();
        lblRow1Desc = new javax.swing.JLabel();
        lblRow1Qty = new javax.swing.JLabel();
        lblRow1Price = new javax.swing.JLabel();
        lblRow1Amount = new javax.swing.JLabel();
        lblRow2Desc = new javax.swing.JLabel();
        lblRow2Qty = new javax.swing.JLabel();
        lblRow2Price = new javax.swing.JLabel();
        lblRow2Amount = new javax.swing.JLabel();
        lblRow3Desc = new javax.swing.JLabel();
        lblRow3Qty = new javax.swing.JLabel();
        lblRow3Price = new javax.swing.JLabel();
        lblRow3Amount = new javax.swing.JLabel();
        lblRow4Desc = new javax.swing.JLabel();
        lblRow4Qty = new javax.swing.JLabel();
        lblRow4Price = new javax.swing.JLabel();
        lblRow4Amount = new javax.swing.JLabel();
        lblRow5Desc = new javax.swing.JLabel();
        lblRow5Qty = new javax.swing.JLabel();
        lblRow5Price = new javax.swing.JLabel();
        lblRow5Amount = new javax.swing.JLabel();
        lblSubtotalTitle = new javax.swing.JLabel();
        lblSubtotalValue = new javax.swing.JLabel();
        lblTaxTitle = new javax.swing.JLabel();
        lblTaxValue = new javax.swing.JLabel();
        jSeparatorInvoice2 = new javax.swing.JSeparator();
        lblGrandTotalTitle = new javax.swing.JLabel();
        lblGrandTotalValue = new javax.swing.JLabel();
        btnPrintInvoice = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Guest = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        Mealtime = new javax.swing.JButton();
        Billing = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(null);

        jPanelHeader.setBackground(new java.awt.Color(211, 228, 245));
        jPanelHeader.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(75, 85, 99));
        lblTitle.setText("Billing & Invoicing");
        jPanelHeader.add(lblTitle);
        lblTitle.setBounds(15, 10, 200, 25);

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(75, 85, 99));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Frontdesk");
        jPanelHeader.add(lblRole);
        lblRole.setBounds(430, 10, 100, 25);

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        jPanelHeader.add(lblUserIcon);
        lblUserIcon.setBounds(540, 10, 25, 25);

        jPanelMain.add(jPanelHeader);
        jPanelHeader.setBounds(20, 15, 580, 45);

        jPanelInvoiceContainer.setBackground(new java.awt.Color(211, 228, 245));
        jPanelInvoiceContainer.setLayout(null);

        jPanelInvoiceCard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInvoiceCard.setLayout(null);

        lblGuestIdTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblGuestIdTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblGuestIdTitle.setText("GUEST ID");
        jPanelInvoiceCard.add(lblGuestIdTitle);
        lblGuestIdTitle.setBounds(20, 20, 100, 15);

        lblGuestIdValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGuestIdValue.setForeground(new java.awt.Color(15, 23, 42));
        lblGuestIdValue.setText("001");
        jPanelInvoiceCard.add(lblGuestIdValue);
        lblGuestIdValue.setBounds(20, 35, 100, 20);

        lblRoomIdTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblRoomIdTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblRoomIdTitle.setText("ROOM ID");
        jPanelInvoiceCard.add(lblRoomIdTitle);
        lblRoomIdTitle.setBounds(170, 20, 100, 15);

        lblRoomIdValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRoomIdValue.setForeground(new java.awt.Color(15, 23, 42));
        lblRoomIdValue.setText("001");
        jPanelInvoiceCard.add(lblRoomIdValue);
        lblRoomIdValue.setBounds(170, 35, 100, 20);

        lblStayPeriodTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblStayPeriodTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblStayPeriodTitle.setText("STAY PERIOD");
        jPanelInvoiceCard.add(lblStayPeriodTitle);
        lblStayPeriodTitle.setBounds(320, 20, 150, 15);

        lblStayPeriodValue.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStayPeriodValue.setForeground(new java.awt.Color(15, 23, 42));
        lblStayPeriodValue.setText("Oct 14 - Oct 18 (4 Nights)");
        jPanelInvoiceCard.add(lblStayPeriodValue);
        lblStayPeriodValue.setBounds(320, 35, 210, 20);
        jPanelInvoiceCard.add(jSeparatorInvoice);
        jSeparatorInvoice.setBounds(20, 65, 510, 5);

        lblColDesc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblColDesc.setForeground(new java.awt.Color(15, 23, 42));
        lblColDesc.setText("DESCRIPTION");
        jPanelInvoiceCard.add(lblColDesc);
        lblColDesc.setBounds(20, 75, 200, 20);

        lblColQty.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblColQty.setForeground(new java.awt.Color(15, 23, 42));
        lblColQty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColQty.setText("QUANTITY");
        jPanelInvoiceCard.add(lblColQty);
        lblColQty.setBounds(250, 75, 90, 20);

        lblColPrice.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblColPrice.setForeground(new java.awt.Color(15, 23, 42));
        lblColPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColPrice.setText("UNIT PRICE");
        jPanelInvoiceCard.add(lblColPrice);
        lblColPrice.setBounds(350, 75, 90, 20);

        lblColAmount.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblColAmount.setForeground(new java.awt.Color(15, 23, 42));
        lblColAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColAmount.setText("AMOUNT");
        jPanelInvoiceCard.add(lblColAmount);
        lblColAmount.setBounds(450, 75, 80, 20);

        lblRow1Desc.setForeground(new java.awt.Color(30, 41, 55));
        lblRow1Desc.setText(" ");
        jPanelInvoiceCard.add(lblRow1Desc);
        lblRow1Desc.setBounds(20, 100, 200, 20);

        lblRow1Qty.setForeground(new java.awt.Color(30, 41, 55));
        lblRow1Qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow1Qty.setText("4 Nights");
        jPanelInvoiceCard.add(lblRow1Qty);
        lblRow1Qty.setBounds(250, 100, 90, 20);

        lblRow1Price.setForeground(new java.awt.Color(30, 41, 55));
        lblRow1Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow1Price.setText("$250.00");
        jPanelInvoiceCard.add(lblRow1Price);
        lblRow1Price.setBounds(350, 100, 90, 20);

        lblRow1Amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRow1Amount.setForeground(new java.awt.Color(15, 23, 42));
        lblRow1Amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow1Amount.setText("$1,000.00");
        jPanelInvoiceCard.add(lblRow1Amount);
        lblRow1Amount.setBounds(450, 100, 80, 20);

        lblRow2Desc.setForeground(new java.awt.Color(30, 41, 55));
        lblRow2Desc.setText("Room Service (Oct 15 - Dinner)");
        jPanelInvoiceCard.add(lblRow2Desc);
        lblRow2Desc.setBounds(20, 125, 200, 20);

        lblRow2Qty.setForeground(new java.awt.Color(30, 41, 55));
        lblRow2Qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow2Qty.setText("1");
        jPanelInvoiceCard.add(lblRow2Qty);
        lblRow2Qty.setBounds(250, 125, 90, 20);

        lblRow2Price.setForeground(new java.awt.Color(30, 41, 55));
        lblRow2Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow2Price.setText("$65.50");
        jPanelInvoiceCard.add(lblRow2Price);
        lblRow2Price.setBounds(350, 125, 90, 20);

        lblRow2Amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRow2Amount.setForeground(new java.awt.Color(15, 23, 42));
        lblRow2Amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow2Amount.setText("$65.50");
        jPanelInvoiceCard.add(lblRow2Amount);
        lblRow2Amount.setBounds(450, 125, 80, 20);

        lblRow3Desc.setForeground(new java.awt.Color(30, 41, 55));
        lblRow3Desc.setText("Food orders");
        jPanelInvoiceCard.add(lblRow3Desc);
        lblRow3Desc.setBounds(20, 150, 200, 20);

        lblRow3Qty.setForeground(new java.awt.Color(30, 41, 55));
        lblRow3Qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow3Qty.setText("1");
        jPanelInvoiceCard.add(lblRow3Qty);
        lblRow3Qty.setBounds(250, 150, 90, 20);

        lblRow3Price.setForeground(new java.awt.Color(30, 41, 55));
        lblRow3Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow3Price.setText("$145.00");
        jPanelInvoiceCard.add(lblRow3Price);
        lblRow3Price.setBounds(350, 150, 90, 20);

        lblRow3Amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRow3Amount.setForeground(new java.awt.Color(15, 23, 42));
        lblRow3Amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow3Amount.setText("$145.00");
        jPanelInvoiceCard.add(lblRow3Amount);
        lblRow3Amount.setBounds(450, 150, 80, 20);

        lblRow4Desc.setForeground(new java.awt.Color(30, 41, 55));
        lblRow4Desc.setText("Laundry Service");
        jPanelInvoiceCard.add(lblRow4Desc);
        lblRow4Desc.setBounds(20, 175, 200, 20);

        lblRow4Qty.setForeground(new java.awt.Color(30, 41, 55));
        lblRow4Qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow4Qty.setText("3 Items");
        jPanelInvoiceCard.add(lblRow4Qty);
        lblRow4Qty.setBounds(250, 175, 90, 20);

        lblRow4Price.setForeground(new java.awt.Color(30, 41, 55));
        lblRow4Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow4Price.setText("$12.00");
        jPanelInvoiceCard.add(lblRow4Price);
        lblRow4Price.setBounds(350, 175, 90, 20);

        lblRow4Amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRow4Amount.setForeground(new java.awt.Color(15, 23, 42));
        lblRow4Amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow4Amount.setText("$36.00");
        jPanelInvoiceCard.add(lblRow4Amount);
        lblRow4Amount.setBounds(450, 175, 80, 20);

        lblRow5Desc.setForeground(new java.awt.Color(30, 41, 55));
        lblRow5Desc.setText("Mini Bar Consumption");
        jPanelInvoiceCard.add(lblRow5Desc);
        lblRow5Desc.setBounds(20, 200, 200, 20);

        lblRow5Qty.setForeground(new java.awt.Color(30, 41, 55));
        lblRow5Qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow5Qty.setText("—");
        jPanelInvoiceCard.add(lblRow5Qty);
        lblRow5Qty.setBounds(250, 200, 90, 20);

        lblRow5Price.setForeground(new java.awt.Color(30, 41, 55));
        lblRow5Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow5Price.setText("—");
        jPanelInvoiceCard.add(lblRow5Price);
        lblRow5Price.setBounds(350, 200, 90, 20);

        lblRow5Amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRow5Amount.setForeground(new java.awt.Color(15, 23, 42));
        lblRow5Amount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRow5Amount.setText("$22.00");
        jPanelInvoiceCard.add(lblRow5Amount);
        lblRow5Amount.setBounds(450, 200, 80, 20);

        lblSubtotalTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtotalTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblSubtotalTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalTitle.setText("Subtotal");
        jPanelInvoiceCard.add(lblSubtotalTitle);
        lblSubtotalTitle.setBounds(320, 235, 120, 15);

        lblSubtotalValue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtotalValue.setForeground(new java.awt.Color(15, 23, 42));
        lblSubtotalValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalValue.setText("$1,268.50");
        jPanelInvoiceCard.add(lblSubtotalValue);
        lblSubtotalValue.setBounds(450, 235, 80, 15);

        lblTaxTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTaxTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblTaxTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxTitle.setText("Tax (8%)");
        jPanelInvoiceCard.add(lblTaxTitle);
        lblTaxTitle.setBounds(320, 255, 120, 15);

        lblTaxValue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTaxValue.setForeground(new java.awt.Color(15, 23, 42));
        lblTaxValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxValue.setText("$101.48");
        jPanelInvoiceCard.add(lblTaxValue);
        lblTaxValue.setBounds(450, 255, 80, 15);
        jPanelInvoiceCard.add(jSeparatorInvoice2);
        jSeparatorInvoice2.setBounds(320, 275, 210, 5);

        lblGrandTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGrandTotalTitle.setForeground(new java.awt.Color(15, 23, 42));
        lblGrandTotalTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrandTotalTitle.setText("Grand Total");
        jPanelInvoiceCard.add(lblGrandTotalTitle);
        lblGrandTotalTitle.setBounds(300, 285, 120, 25);

        lblGrandTotalValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGrandTotalValue.setForeground(new java.awt.Color(15, 23, 42));
        lblGrandTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrandTotalValue.setText("$1,369.98");
        jPanelInvoiceCard.add(lblGrandTotalValue);
        lblGrandTotalValue.setBounds(430, 285, 100, 25);

        jPanelInvoiceContainer.add(jPanelInvoiceCard);
        jPanelInvoiceCard.setBounds(15, 15, 550, 330);

        btnPrintInvoice.setBackground(new java.awt.Color(37, 99, 235));
        btnPrintInvoice.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnPrintInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintInvoice.setText("🖨️ Print Invoice");
        jPanelInvoiceContainer.add(btnPrintInvoice);
        btnPrintInvoice.setBounds(435, 360, 130, 30);

        jPanelMain.add(jPanelInvoiceContainer);
        jPanelInvoiceContainer.setBounds(20, 75, 580, 405);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelMain.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 10, 500);

        getContentPane().add(jPanelMain);
        jPanelMain.setBounds(180, 0, 620, 500);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(37, 99, 235));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HMS");
        jPanelSidebar.add(lblLogo);
        lblLogo.setBounds(10, 30, 140, 30);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Dashboard.setText("  Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        Dashboard.setFocusPainted(false);
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard.addActionListener(this::DashboardActionPerformed);
        jPanelSidebar.add(Dashboard);
        Dashboard.setBounds(10, 80, 160, 35);

        Guest.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Guest.setText(" Guest");
        Guest.setBorderPainted(false);
        Guest.setContentAreaFilled(false);
        Guest.setFocusPainted(false);
        Guest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Guest.addActionListener(this::GuestActionPerformed);
        jPanelSidebar.add(Guest);
        Guest.setBounds(10, 120, 160, 35);

        Booking.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Booking.setText(" Booking");
        Booking.setBorderPainted(false);
        Booking.setContentAreaFilled(false);
        Booking.setFocusPainted(false);
        Booking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Booking.addActionListener(this::BookingActionPerformed);
        jPanelSidebar.add(Booking);
        Booking.setBounds(10, 160, 160, 35);

        Mealtime.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Mealtime.setText(" Mealtime");
        Mealtime.setBorderPainted(false);
        Mealtime.setContentAreaFilled(false);
        Mealtime.setFocusPainted(false);
        Mealtime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mealtime.addActionListener(this::MealtimeActionPerformed);
        jPanelSidebar.add(Mealtime);
        Mealtime.setBounds(10, 200, 160, 35);

        Billing.setBackground(new java.awt.Color(211, 228, 245));
        Billing.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Billing.setForeground(new java.awt.Color(37, 99, 235));
        Billing.setText(" Billing");
        Billing.setBorderPainted(false);
        Billing.setFocusPainted(false);
        Billing.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Billing.addActionListener(this::BillingActionPerformed);
        jPanelSidebar.add(Billing);
        Billing.setBounds(10, 240, 160, 35);

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Logout.setText(" Logout");
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setFocusPainted(false);
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.addActionListener(this::LogoutActionPerformed);
        jPanelSidebar.add(Logout);
        Logout.setBounds(10, 280, 160, 35);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 180, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestActionPerformed

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingActionPerformed

    private void MealtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealtimeActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillingActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Billing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Billing;
    private javax.swing.JButton Booking;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Guest;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Mealtime;
    private javax.swing.JButton btnPrintInvoice;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelInvoiceCard;
    private javax.swing.JPanel jPanelInvoiceContainer;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparatorInvoice;
    private javax.swing.JSeparator jSeparatorInvoice2;
    private javax.swing.JLabel lblColAmount;
    private javax.swing.JLabel lblColDesc;
    private javax.swing.JLabel lblColPrice;
    private javax.swing.JLabel lblColQty;
    private javax.swing.JLabel lblGrandTotalTitle;
    private javax.swing.JLabel lblGrandTotalValue;
    private javax.swing.JLabel lblGuestIdTitle;
    private javax.swing.JLabel lblGuestIdValue;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoomIdTitle;
    private javax.swing.JLabel lblRoomIdValue;
    private javax.swing.JLabel lblRow1Amount;
    private javax.swing.JLabel lblRow1Desc;
    private javax.swing.JLabel lblRow1Price;
    private javax.swing.JLabel lblRow1Qty;
    private javax.swing.JLabel lblRow2Amount;
    private javax.swing.JLabel lblRow2Desc;
    private javax.swing.JLabel lblRow2Price;
    private javax.swing.JLabel lblRow2Qty;
    private javax.swing.JLabel lblRow3Amount;
    private javax.swing.JLabel lblRow3Desc;
    private javax.swing.JLabel lblRow3Price;
    private javax.swing.JLabel lblRow3Qty;
    private javax.swing.JLabel lblRow4Amount;
    private javax.swing.JLabel lblRow4Desc;
    private javax.swing.JLabel lblRow4Price;
    private javax.swing.JLabel lblRow4Qty;
    private javax.swing.JLabel lblRow5Amount;
    private javax.swing.JLabel lblRow5Desc;
    private javax.swing.JLabel lblRow5Price;
    private javax.swing.JLabel lblRow5Qty;
    private javax.swing.JLabel lblStayPeriodTitle;
    private javax.swing.JLabel lblStayPeriodValue;
    private javax.swing.JLabel lblSubtotalTitle;
    private javax.swing.JLabel lblSubtotalValue;
    private javax.swing.JLabel lblTaxTitle;
    private javax.swing.JLabel lblTaxValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserIcon;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblRole() { return lblRole; }
    public javax.swing.JLabel getLblGuestIdValue() { return lblGuestIdValue; }
    public javax.swing.JLabel getLblRoomIdValue() { return lblRoomIdValue; }
    public javax.swing.JLabel getLblStayPeriodValue() { return lblStayPeriodValue; }
    public javax.swing.JLabel getLblRow1Qty() { return lblRow1Qty; }
    public javax.swing.JLabel getLblRow1Price() { return lblRow1Price; }
    public javax.swing.JLabel getLblRow1Amount() { return lblRow1Amount; }
    public javax.swing.JLabel getLblRow2Qty() { return lblRow2Qty; }
    public javax.swing.JLabel getLblRow2Price() { return lblRow2Price; }
    public javax.swing.JLabel getLblRow2Amount() { return lblRow2Amount; }
    public javax.swing.JLabel getLblRow3Qty() { return lblRow3Qty; }
    public javax.swing.JLabel getLblRow3Price() { return lblRow3Price; }
    public javax.swing.JLabel getLblRow3Amount() { return lblRow3Amount; }
    public javax.swing.JLabel getLblRow4Qty() { return lblRow4Qty; }
    public javax.swing.JLabel getLblRow4Price() { return lblRow4Price; }
    public javax.swing.JLabel getLblRow4Amount() { return lblRow4Amount; }
    public javax.swing.JLabel getLblRow5Qty() { return lblRow5Qty; }
    public javax.swing.JLabel getLblRow5Price() { return lblRow5Price; }
    public javax.swing.JLabel getLblRow5Amount() { return lblRow5Amount; }
    public javax.swing.JLabel getLblSubtotalValue() { return lblSubtotalValue; }
    public javax.swing.JLabel getLblTaxValue() { return lblTaxValue; }
    public javax.swing.JLabel getLblGrandTotalValue() { return lblGrandTotalValue; }
    public javax.swing.JButton getBtnDashboard() { return Dashboard; }
    public javax.swing.JButton getBtnLogout() { return Logout; }
    public javax.swing.JButton getBtnPrintInvoice() { return btnPrintInvoice; }
}
