/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;

/**
 *
 * @author i3
 */
public class BookingManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingManagement.class.getName());

    /**
     * Creates new form BookingManagement
     */
    public BookingManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Guest = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        Mealtime = new javax.swing.JButton();
        Billing = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabelDateRange = new javax.swing.JLabel();
        jLabelRoomType = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPaneBookings = new javax.swing.JScrollPane();
        jTableBookings = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBoxRoomType = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(37, 99, 235));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HMS");
        jPanelSidebar.add(lblLogo);
        lblLogo.setBounds(10, 30, 140, 30);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Dashboard.setText("  Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        Dashboard.setFocusPainted(false);
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard.addActionListener(this::DashboardActionPerformed);
        jPanelSidebar.add(Dashboard);
        Dashboard.setBounds(10, 80, 160, 35);

        Guest.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Guest.setText(" Guest");
        Guest.setBorderPainted(false);
        Guest.setContentAreaFilled(false);
        Guest.setFocusPainted(false);
        Guest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Guest.addActionListener(this::GuestActionPerformed);
        jPanelSidebar.add(Guest);
        Guest.setBounds(10, 120, 160, 35);

        Booking.setBackground(new java.awt.Color(211, 228, 245));
        Booking.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Booking.setForeground(new java.awt.Color(37, 99, 235));
        Booking.setText(" Booking");
        Booking.setBorderPainted(false);
        Booking.setFocusPainted(false);
        Booking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Booking.addActionListener(this::BookingActionPerformed);
        jPanelSidebar.add(Booking);
        Booking.setBounds(10, 160, 160, 35);

        Mealtime.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Mealtime.setText(" Mealtime");
        Mealtime.setBorderPainted(false);
        Mealtime.setContentAreaFilled(false);
        Mealtime.setFocusPainted(false);
        Mealtime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mealtime.addActionListener(this::MealtimeActionPerformed);
        jPanelSidebar.add(Mealtime);
        Mealtime.setBounds(10, 200, 160, 35);

        Billing.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Billing.setText(" Billing");
        Billing.setBorderPainted(false);
        Billing.setContentAreaFilled(false);
        Billing.setFocusPainted(false);
        Billing.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Billing.addActionListener(this::BillingActionPerformed);
        jPanelSidebar.add(Billing);
        Billing.setBounds(10, 240, 160, 35);

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Logout.setText(" Logout");
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setFocusPainted(false);
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.addActionListener(this::LogoutActionPerformed);
        jPanelSidebar.add(Logout);
        Logout.setBounds(10, 280, 160, 35);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 180, 500);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(211, 228, 245));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(75, 85, 99));
        jLabelTitle.setText("Booking Management");
        jPanelHeader.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, 220, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 85, 99));
        jLabel1.setText("FrontDesk");
        jPanelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 80, -1));

        jPanelMain.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 45));

        jPanelContent.setBackground(new java.awt.Color(211, 228, 245));
        jPanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearch.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelSearch.setForeground(new java.awt.Color(75, 85, 99));
        jLabelSearch.setText("SEARCH GUEST / ID");
        jPanelContent.add(jLabelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 15));

        jTextFieldSearch.setForeground(new java.awt.Color(156, 163, 169));
        jTextFieldSearch.addActionListener(this::jTextFieldSearchActionPerformed);
        jPanelContent.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 28));

        jLabelDateRange.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelDateRange.setForeground(new java.awt.Color(75, 85, 99));
        jLabelDateRange.setText("DATE ");
        jPanelContent.add(jLabelDateRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, 15));

        jLabelRoomType.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelRoomType.setForeground(new java.awt.Color(75, 85, 99));
        jLabelRoomType.setText("ROOM TYPE");
        jPanelContent.add(jLabelRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 90, 15));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(75, 85, 99));
        jLabelStatus.setText("STATUS");
        jPanelContent.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 80, 15));

        jTableBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Guest Name", "Room", "Room Type", "Stay Duration", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBookings.setGridColor(new java.awt.Color(229, 231, 235));
        jTableBookings.setRowHeight(38);
        jTableBookings.setSelectionBackground(new java.awt.Color(239, 246, 255));
        jTableBookings.setSelectionForeground(new java.awt.Color(30, 64, 175));
        jTableBookings.setShowHorizontalLines(true);
        jTableBookings.getTableHeader().setReorderingAllowed(false);
        jScrollPaneBookings.setViewportView(jTableBookings);

        jScrollPane1.setViewportView(jScrollPaneBookings);

        jPanelContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, 250));
        jPanelContent.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 130, 30));

        jComboBoxRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Single Bed", "Double Bed", "VIP" }));
        jComboBoxRoomType.addActionListener(this::jComboBoxRoomTypeActionPerformed);
        jPanelContent.add(jComboBoxRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, 30));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "CheckedIn", "CheckedOut" }));
        jPanelContent.add(jComboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 120, 30));

        jPanelMain.add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 590, 380));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelMain.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        getContentPane().add(jPanelMain);
        jPanelMain.setBounds(180, 0, 620, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestActionPerformed

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingActionPerformed

    private void MealtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealtimeActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillingActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jComboBoxRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoomTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Billing;
    private javax.swing.JButton Booking;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Guest;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Mealtime;
    private javax.swing.JComboBox<String> jComboBoxRoomType;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDateRange;
    private javax.swing.JLabel jLabelRoomType;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneBookings;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableBookings;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTable() { return jTableBookings; }
    public javax.swing.JTextField getTxtSearch() { return jTextFieldSearch; }
    public javax.swing.JComboBox getComboRoomType() { return jComboBoxRoomType; }
    public javax.swing.JComboBox getComboStatus() { return jComboBoxStatus; }
    public JDateChooser getTxtDate() { return jDateChooser1; }
    public javax.swing.JButton getBtnDashboard() { return Dashboard; }
    public javax.swing.JButton getBtnGuest() { return Guest; }
    public javax.swing.JButton getBtnBooking() { return Booking; }
    public javax.swing.JButton getBtnMealtime() { return Mealtime; }
    public javax.swing.JButton getBtnBilling() { return Billing; }
    public javax.swing.JButton getBtnLogout() { return Logout; }
}
