package view;

/**
 * Room Browsing View Frame
 * @author Dell
 */
public class BookRoom extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookRoom.class.getName());

    /**
     * Creates new form BookRoom
     */
    public BookRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelHeaderTitle = new javax.swing.JLabel();
        jLabelGuestRole = new javax.swing.JLabel();
        jLabelAvatar = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelCol1 = new javax.swing.JPanel();
        jLabelVipImage = new javax.swing.JLabel();
        jLabelVipTitle = new javax.swing.JLabel();
        jLabel_vip_price = new javax.swing.JLabel();
        jLabelVipPerNight = new javax.swing.JLabel();
        jLabelVipAreaIcon = new javax.swing.JLabel();
        jLabel_vip_size = new javax.swing.JLabel();
        jLabelVipBedIcon = new javax.swing.JLabel();
        jLabel_vip_bed = new javax.swing.JLabel();
        jScrollPaneVip = new javax.swing.JScrollPane();
        jTextArea_vip_desc = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jPanelCol2 = new javax.swing.JPanel();
        jLabelDoubleImage = new javax.swing.JLabel();
        jLabelDoubleTitle = new javax.swing.JLabel();
        jLabel_double_price = new javax.swing.JLabel();
        jLabelDoublePerNight = new javax.swing.JLabel();
        jLabelDoubleAreaIcon = new javax.swing.JLabel();
        jLabel_double_size = new javax.swing.JLabel();
        jLabelDoubleBedIcon = new javax.swing.JLabel();
        jLabel_double_bed = new javax.swing.JLabel();
        jScrollPaneDouble = new javax.swing.JScrollPane();
        jTextArea_double_desc = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jPanelCol3 = new javax.swing.JPanel();
        jLabelSingleImage = new javax.swing.JLabel();
        jLabelSingleTitle = new javax.swing.JLabel();
        jLabel_single_price = new javax.swing.JLabel();
        jLabelSinglePerNight = new javax.swing.JLabel();
        jLabelSingleAreaIcon = new javax.swing.JLabel();
        jLabel_single_size = new javax.swing.JLabel();
        jLabelSingleBedIcon = new javax.swing.JLabel();
        jLabel_single_bed = new javax.swing.JLabel();
        jScrollPaneSingle = new javax.swing.JScrollPane();
        jTextArea_single_desc = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnRooms = new javax.swing.JButton();
        btnDiscounts = new javax.swing.JButton();
        btnStaffs = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnSystemSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Browsing");
        setMinimumSize(new java.awt.Dimension(810, 535));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanelHeader.setBackground(new java.awt.Color(211, 228, 245));
        jPanelHeader.setLayout(null);

        jLabelHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHeaderTitle.setForeground(new java.awt.Color(75, 75, 75));
        jLabelHeaderTitle.setText("Room Browsing");
        jPanelHeader.add(jLabelHeaderTitle);
        jLabelHeaderTitle.setBounds(15, 12, 200, 20);

        jLabelGuestRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelGuestRole.setForeground(new java.awt.Color(75, 75, 75));
        jLabelGuestRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGuestRole.setText("Guest");
        jPanelHeader.add(jLabelGuestRole);
        jLabelGuestRole.setBounds(480, 12, 60, 20);

        jLabelAvatar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvatar.setText("👤");
        jLabelAvatar.setOpaque(true);
        jPanelHeader.add(jLabelAvatar);
        jLabelAvatar.setBounds(555, 8, 30, 30);

        jPanel2.add(jPanelHeader);
        jPanelHeader.setBounds(20, 15, 600, 45);

        jPanelContainer.setBackground(new java.awt.Color(211, 228, 245));
        jPanelContainer.setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(17, 24, 39));
        jLabelTitle.setText("Available Accommodations");
        jPanelContainer.add(jLabelTitle);
        jLabelTitle.setBounds(20, 15, 300, 25);

        jPanelCol1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCol1.setLayout(null);

        jLabelVipImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vip.jpg"))); // NOI18N
        jPanelCol1.add(jLabelVipImage);
        jLabelVipImage.setBounds(10, 10, 180, 130);

        jLabelVipTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelVipTitle.setForeground(new java.awt.Color(17, 24, 39));
        jLabelVipTitle.setText("VIP");
        jPanelCol1.add(jLabelVipTitle);
        jLabelVipTitle.setBounds(10, 140, 90, 20);

        jLabel_vip_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_vip_price.setForeground(new java.awt.Color(17, 24, 39));
        jLabel_vip_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_vip_price.setText("$850");
        jPanelCol1.add(jLabel_vip_price);
        jLabel_vip_price.setBounds(130, 140, 65, 20);

        jLabelVipPerNight.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelVipPerNight.setForeground(new java.awt.Color(156, 163, 175));
        jLabelVipPerNight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVipPerNight.setText("PER NIGHT");
        jPanelCol1.add(jLabelVipPerNight);
        jLabelVipPerNight.setBounds(130, 160, 65, 12);

        jLabelVipAreaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_area.png"))); // NOI18N
        jPanelCol1.add(jLabelVipAreaIcon);
        jLabelVipAreaIcon.setBounds(10, 170, 14, 14);

        jLabel_vip_size.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_vip_size.setForeground(new java.awt.Color(107, 114, 128));
        jLabel_vip_size.setText("  85m²");
        jPanelCol1.add(jLabel_vip_size);
        jLabel_vip_size.setBounds(30, 170, 40, 14);

        jLabelVipBedIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_bed.png"))); // NOI18N
        jPanelCol1.add(jLabelVipBedIcon);
        jLabelVipBedIcon.setBounds(70, 170, 14, 14);

        jLabel_vip_bed.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_vip_bed.setForeground(new java.awt.Color(107, 114, 128));
        jLabel_vip_bed.setText("  King Size");
        jPanelCol1.add(jLabel_vip_bed);
        jLabel_vip_bed.setBounds(80, 170, 80, 14);

        jScrollPaneVip.setBorder(null);
        jScrollPaneVip.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneVip.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea_vip_desc.setEditable(false);
        jTextArea_vip_desc.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_vip_desc.setColumns(20);
        jTextArea_vip_desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextArea_vip_desc.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea_vip_desc.setLineWrap(true);
        jTextArea_vip_desc.setRows(5);
        jTextArea_vip_desc.setText("Our pinnacle of luxury featuring a\nprivate lounge, marble bathroom\nwith a soaking tub, and priority\nconcierge access.");
        jTextArea_vip_desc.setWrapStyleWord(true);
        jTextArea_vip_desc.setBorder(null);
        jScrollPaneVip.setViewportView(jTextArea_vip_desc);

        jPanelCol1.add(jScrollPaneVip);
        jScrollPaneVip.setBounds(10, 190, 180, 80);

        jButton6.setBackground(new java.awt.Color(37, 99, 235));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BOOK NOW");
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jPanelCol1.add(jButton6);
        jButton6.setBounds(30, 280, 155, 35);

        jPanelContainer.add(jPanelCol1);
        jPanelCol1.setBounds(10, 60, 200, 330);

        jPanelCol2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCol2.setLayout(null);

        jLabelDoubleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doble.jpg"))); // NOI18N
        jPanelCol2.add(jLabelDoubleImage);
        jLabelDoubleImage.setBounds(5, 10, 180, 130);

        jLabelDoubleTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelDoubleTitle.setForeground(new java.awt.Color(17, 24, 39));
        jLabelDoubleTitle.setText("Double Bed Room");
        jPanelCol2.add(jLabelDoubleTitle);
        jLabelDoubleTitle.setBounds(10, 140, 100, 20);

        jLabel_double_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_double_price.setForeground(new java.awt.Color(17, 24, 39));
        jLabel_double_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_double_price.setText("$420");
        jPanelCol2.add(jLabel_double_price);
        jLabel_double_price.setBounds(120, 140, 55, 20);

        jLabelDoublePerNight.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelDoublePerNight.setForeground(new java.awt.Color(156, 163, 175));
        jLabelDoublePerNight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDoublePerNight.setText("PER NIGHT");
        jPanelCol2.add(jLabelDoublePerNight);
        jLabelDoublePerNight.setBounds(120, 160, 55, 12);

        jLabelDoubleAreaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_area.png"))); // NOI18N
        jPanelCol2.add(jLabelDoubleAreaIcon);
        jLabelDoubleAreaIcon.setBounds(10, 170, 14, 14);

        jLabel_double_size.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_double_size.setForeground(new java.awt.Color(107, 114, 128));
        jLabel_double_size.setText("  45m²");
        jPanelCol2.add(jLabel_double_size);
        jLabel_double_size.setBounds(20, 170, 40, 14);

        jLabelDoubleBedIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_bed.png"))); // NOI18N
        jPanelCol2.add(jLabelDoubleBedIcon);
        jLabelDoubleBedIcon.setBounds(70, 170, 14, 14);

        jLabel_double_bed.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_double_bed.setForeground(new java.awt.Color(107, 114, 128));
        jLabel_double_bed.setText("  2 Doubles");
        jPanelCol2.add(jLabel_double_bed);
        jLabel_double_bed.setBounds(80, 170, 80, 14);

        jScrollPaneDouble.setBorder(null);
        jScrollPaneDouble.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneDouble.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea_double_desc.setEditable(false);
        jTextArea_double_desc.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_double_desc.setColumns(20);
        jTextArea_double_desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextArea_double_desc.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea_double_desc.setLineWrap(true);
        jTextArea_double_desc.setRows(5);
        jTextArea_double_desc.setText("Perfect for families or business\nassociates, offering spacious\nlayouts and a fully equipped\nergonomic workspace.");
        jTextArea_double_desc.setWrapStyleWord(true);
        jTextArea_double_desc.setBorder(null);
        jScrollPaneDouble.setViewportView(jTextArea_double_desc);

        jPanelCol2.add(jScrollPaneDouble);
        jScrollPaneDouble.setBounds(15, 190, 160, 80);

        jButton7.setBackground(new java.awt.Color(37, 99, 235));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("BOOK NOW");
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);
        jPanelCol2.add(jButton7);
        jButton7.setBounds(20, 280, 155, 35);

        jPanelContainer.add(jPanelCol2);
        jPanelCol2.setBounds(220, 60, 190, 330);

        jPanelCol3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCol3.setLayout(null);

        jLabelSingleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/singal.jpg"))); // NOI18N
        jPanelCol3.add(jLabelSingleImage);
        jLabelSingleImage.setBounds(5, 10, 180, 120);

        jLabelSingleTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelSingleTitle.setForeground(new java.awt.Color(17, 24, 39));
        jLabelSingleTitle.setText("Single Bed Room");
        jPanelCol3.add(jLabelSingleTitle);
        jLabelSingleTitle.setBounds(10, 140, 110, 20);

        jLabel_single_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_single_price.setForeground(new java.awt.Color(17, 24, 39));
        jLabel_single_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_single_price.setText("$295");
        jPanelCol3.add(jLabel_single_price);
        jLabel_single_price.setBounds(110, 140, 55, 20);

        jLabelSinglePerNight.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabelSinglePerNight.setForeground(new java.awt.Color(156, 163, 175));
        jLabelSinglePerNight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSinglePerNight.setText("PER NIGHT");
        jPanelCol3.add(jLabelSinglePerNight);
        jLabelSinglePerNight.setBounds(110, 160, 55, 12);

        jLabelSingleAreaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_area.png"))); // NOI18N
        jPanelCol3.add(jLabelSingleAreaIcon);
        jLabelSingleAreaIcon.setBounds(10, 170, 14, 14);

        jLabel_single_size.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_single_size.setForeground(new java.awt.Color(107, 114, 128));
        jLabel_single_size.setText("  30m²");
        jPanelCol3.add(jLabel_single_size);
        jLabel_single_size.setBounds(20, 170, 40, 14);

        jLabelSingleBedIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_bed.png"))); // NOI18N
        jPanelCol3.add(jLabelSingleBedIcon);
        jLabelSingleBedIcon.setBounds(70, 170, 14, 14);

        jLabel_single_bed.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_single_bed.setForeground(new java.awt.Color(107, 114, 128));
        jLabel_single_bed.setText("  1 Queen");
        jPanelCol3.add(jLabel_single_bed);
        jLabel_single_bed.setBounds(80, 170, 80, 14);

        jScrollPaneSingle.setBorder(null);
        jScrollPaneSingle.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneSingle.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea_single_desc.setEditable(false);
        jTextArea_single_desc.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_single_desc.setColumns(20);
        jTextArea_single_desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextArea_single_desc.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea_single_desc.setLineWrap(true);
        jTextArea_single_desc.setRows(5);
        jTextArea_single_desc.setText("An efficient and cozy space\ndesigned for the modern solo\ntraveler, prioritizing comfort and\nconnectivity.");
        jTextArea_single_desc.setWrapStyleWord(true);
        jTextArea_single_desc.setBorder(null);
        jScrollPaneSingle.setViewportView(jTextArea_single_desc);

        jPanelCol3.add(jScrollPaneSingle);
        jScrollPaneSingle.setBounds(10, 190, 170, 80);

        jButton9.setBackground(new java.awt.Color(37, 99, 235));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("BOOK NOW");
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jPanelCol3.add(jButton9);
        jButton9.setBounds(20, 280, 155, 35);

        jPanelContainer.add(jPanelCol3);
        jPanelCol3.setBounds(420, 60, 190, 330);

        jPanel2.add(jPanelContainer);
        jPanelContainer.setBounds(10, 75, 620, 410);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 3, 500);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 0, 650, 500);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(37, 99, 235));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HMS");
        jPanelSidebar.add(lblLogo);
        lblLogo.setBounds(10, 30, 140, 30);

        btnRooms.setBackground(new java.awt.Color(211, 228, 245));
        btnRooms.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnRooms.setForeground(new java.awt.Color(37, 99, 235));
        btnRooms.setText("  Room Browsing");
        btnRooms.setBorderPainted(false);
        btnRooms.setFocusPainted(false);
        btnRooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRooms.addActionListener(this::btnRoomsActionPerformed);
        jPanelSidebar.add(btnRooms);
        btnRooms.setBounds(10, 120, 160, 35);

        btnDiscounts.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDiscounts.setText("  Order Food");
        btnDiscounts.setBorderPainted(false);
        btnDiscounts.setContentAreaFilled(false);
        btnDiscounts.setFocusPainted(false);
        btnDiscounts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDiscounts.addActionListener(this::btnDiscountsActionPerformed);
        jPanelSidebar.add(btnDiscounts);
        btnDiscounts.setBounds(10, 160, 160, 35);

        btnStaffs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnStaffs.setText("  Feedback");
        btnStaffs.setBorderPainted(false);
        btnStaffs.setContentAreaFilled(false);
        btnStaffs.setFocusPainted(false);
        btnStaffs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStaffs.addActionListener(this::btnStaffsActionPerformed);
        jPanelSidebar.add(btnStaffs);
        btnStaffs.setBounds(10, 200, 160, 35);

        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnReports.setText("  Logout");
        btnReports.setBorderPainted(false);
        btnReports.setContentAreaFilled(false);
        btnReports.setFocusPainted(false);
        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReports.addActionListener(this::btnReportsActionPerformed);
        jPanelSidebar.add(btnReports);
        btnReports.setBounds(10, 240, 160, 35);

        btnSystemSetting.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSystemSetting.setText("  Dashboard");
        btnSystemSetting.setBorderPainted(false);
        btnSystemSetting.setContentAreaFilled(false);
        btnSystemSetting.setFocusPainted(false);
        btnSystemSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSystemSetting.addActionListener(this::btnSystemSettingActionPerformed);
        jPanelSidebar.add(btnSystemSetting);
        btnSystemSetting.setBounds(10, 80, 160, 35);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 180, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        // Handled by Controller
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountsActionPerformed
        // Handled in other navigation sections
    }//GEN-LAST:event_btnDiscountsActionPerformed

    private void btnStaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffsActionPerformed
        // Handled by Controller
    }//GEN-LAST:event_btnStaffsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // Handled in other navigation sections
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnSystemSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSystemSettingActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscounts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnStaffs;
    private javax.swing.JButton btnSystemSetting;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabelDoubleAreaIcon;
    private javax.swing.JLabel jLabelDoubleBedIcon;
    private javax.swing.JLabel jLabelDoubleImage;
    private javax.swing.JLabel jLabelDoublePerNight;
    private javax.swing.JLabel jLabelDoubleTitle;
    private javax.swing.JLabel jLabelGuestRole;
    private javax.swing.JLabel jLabelHeaderTitle;
    private javax.swing.JLabel jLabelSingleAreaIcon;
    private javax.swing.JLabel jLabelSingleBedIcon;
    private javax.swing.JLabel jLabelSingleImage;
    private javax.swing.JLabel jLabelSinglePerNight;
    private javax.swing.JLabel jLabelSingleTitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVipAreaIcon;
    private javax.swing.JLabel jLabelVipBedIcon;
    private javax.swing.JLabel jLabelVipImage;
    private javax.swing.JLabel jLabelVipPerNight;
    private javax.swing.JLabel jLabelVipTitle;
    private javax.swing.JLabel jLabel_double_bed;
    private javax.swing.JLabel jLabel_double_price;
    private javax.swing.JLabel jLabel_double_size;
    private javax.swing.JLabel jLabel_single_bed;
    private javax.swing.JLabel jLabel_single_price;
    private javax.swing.JLabel jLabel_single_size;
    private javax.swing.JLabel jLabel_vip_bed;
    private javax.swing.JLabel jLabel_vip_price;
    private javax.swing.JLabel jLabel_vip_size;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCol1;
    private javax.swing.JPanel jPanelCol2;
    private javax.swing.JPanel jPanelCol3;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JScrollPane jScrollPaneDouble;
    private javax.swing.JScrollPane jScrollPaneSingle;
    private javax.swing.JScrollPane jScrollPaneVip;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_double_desc;
    private javax.swing.JTextArea jTextArea_single_desc;
    private javax.swing.JTextArea jTextArea_vip_desc;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblVipPrice() { return jLabel_vip_price; }
    public javax.swing.JLabel getLblVipSize() { return jLabel_vip_size; }
    public javax.swing.JLabel getLblVipBed() { return jLabel_vip_bed; }
    public javax.swing.JTextArea getTxtVipDesc() { return jTextArea_vip_desc; }

    public javax.swing.JLabel getLblDoublePrice() { return jLabel_double_price; }
    public javax.swing.JLabel getLblDoubleSize() { return jLabel_double_size; }
    public javax.swing.JLabel getLblDoubleBed() { return jLabel_double_bed; }
    public javax.swing.JTextArea getTxtDoubleDesc() { return jTextArea_double_desc; }

    public javax.swing.JLabel getLblSinglePrice() { return jLabel_single_price; }
    public javax.swing.JLabel getLblSingleSize() { return jLabel_single_size; }
    public javax.swing.JLabel getLblSingleBed() { return jLabel_single_bed; }
    public javax.swing.JTextArea getTxtSingleDesc() { return jTextArea_single_desc; }

    public javax.swing.JButton getBtnDashboard() { return btnSystemSetting; }
    public javax.swing.JButton getBtnOrderFood() { return btnDiscounts; }
    public javax.swing.JButton getBtnFeedback() { return btnStaffs; }
    public javax.swing.JButton getBtnLogout() { return btnReports; }

    public javax.swing.JButton getBtnBookVip() { return jButton6; }
    public javax.swing.JButton getBtnBookDouble() { return jButton7; }
    public javax.swing.JButton getBtnBookSingle() { return jButton9; }
}
