/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;

/**
 *
 * @author pratikjungsinghthakuri
 */
public class Discount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Discount.class.getName());

    /**
     * Creates new form Discount
     */
    public Discount() {
        initComponents();
        
    }

    

        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
jPanelSidebar = new javax.swing.JPanel();

jLabelLogo = new javax.swing.JLabel();

jButtonDashboard = new javax.swing.JButton();
        jButtonRooms = new javax.swing.JButton();

jButtonDiscount = new javax.swing.JButton();

jButtonStaffs = new javax.swing.JButton();

jButtonSystemSetting = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();

jPanelMain = new javax.swing.JPanel();

jLabelMainTitle = new javax.swing.JLabel();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);
jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

jLabelLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(26, 115, 232));
        jLabelLogo.setText("<html><font color='#1A73E8'><b>⚡ HMS</b></font></html>");
        jPanelSidebar.add(jLabelLogo);
        jLabelLogo.setBounds(24, 24, 170, 40);


jButtonDashboard.setBackground(new java.awt.Color(255, 255, 255));

jButtonDashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDashboard.setForeground(new java.awt.Color(95, 99, 104));
        jButtonDashboard.setBorderPainted(false);
        jButtonDashboard.setContentAreaFilled(false);
        jButtonDashboard.setFocusPainted(false);
        jButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonDashboard.setText("🏠  Dashboard");
        jPanelSidebar.add(jButtonDashboard);
        jButtonDashboard.setBounds(16, 100, 188, 40);
jButtonRooms.setBackground(new java.awt.Color(255, 255, 255));

jButtonRooms.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRooms.setForeground(new java.awt.Color(95, 99, 104));
        jButtonRooms.setBorderPainted(false);
        jButtonRooms.setContentAreaFilled(false);
        jButtonRooms.setFocusPainted(false);
        jButtonRooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonRooms.setText("🔑  Rooms");
        jPanelSidebar.add(jButtonRooms);
        jButtonRooms.setBounds(16, 150, 188, 40);


jButtonDiscount.setBackground(new java.awt.Color(232, 240, 254));
        jButtonDiscount.setForeground(new java.awt.Color(26, 115, 232));
        jButtonDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDiscount.setBorderPainted(false);
        jButtonDiscount.setFocusPainted(false);
        jButtonDiscount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonDiscount.setText("🏷️  Discount & Offers");
        jPanelSidebar.add(jButtonDiscount);
        jButtonDiscount.setBounds(16, 200, 188, 40);


jButtonStaffs.setBackground(new java.awt.Color(255, 255, 255));

jButtonStaffs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonStaffs.setForeground(new java.awt.Color(95, 99, 104));
        jButtonStaffs.setBorderPainted(false);
        jButtonStaffs.setContentAreaFilled(false);
        jButtonStaffs.setFocusPainted(false);
        jButtonStaffs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonStaffs.setText("👥  Staffs");
        jPanelSidebar.add(jButtonStaffs);
        jButtonStaffs.setBounds(16, 250, 188, 40);

jButtonSystemSetting.setBackground(new java.awt.Color(255, 255, 255));
jButtonSystemSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSystemSetting.setForeground(new java.awt.Color(95, 99, 104));
        jButtonSystemSetting.setBorderPainted(false);
        jButtonSystemSetting.setContentAreaFilled(false);
        jButtonSystemSetting.setFocusPainted(false);
        jButtonSystemSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonSystemSetting.setText("⚙️  System Setting");
        jPanelSidebar.add(jButtonSystemSetting);
        jButtonSystemSetting.setBounds(16, 300, 188, 40);

        jButtonReports.setBackground(new java.awt.Color(255, 255, 255));
jButtonReports.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonReports.setForeground(new java.awt.Color(95, 99, 104));
        jButtonReports.setBorderPainted(false);
        jButtonReports.setContentAreaFilled(false);
        jButtonReports.setFocusPainted(false);
        jButtonReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonReports.setText("📊  Reports");
        jPanelSidebar.add(jButtonReports);
        jButtonReports.setBounds(16, 350, 188, 40);

        jButtonLogout.setBackground(new java.awt.Color(255, 255, 255));
jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(95, 99, 104));
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jButtonLogout.setText("🚪  Logout");
        jPanelSidebar.add(jButtonLogout);
        jButtonLogout.setBounds(16, 600, 188, 40);

getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 220, 700);

        jPanelMain.setBackground(new java.awt.Color(245, 246, 248));
        jPanelMain.setLayout(null);

jLabelMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMainTitle.setForeground(new java.awt.Color(32, 33, 36));
        jLabelMainTitle.setText("Discount & Offers");
        jPanelMain.add(jLabelMainTitle);
        jLabelMainTitle.setBounds(30, 24, 300, 40);

getContentPane().add(jPanelMain);
        jPanelMain.setBounds(220, 0, 780, 700);
pack();
        setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Discount().setVisible(true));
    }

    // Variables declaration - do not modify
private javax.swing.JButton jButtonDashboard;

private javax.swing.JButton jButtonDiscount;
    private javax.swing.JButton jButtonLogout;

private javax.swing.JButton jButtonRooms;
    private javax.swing.JButton jButtonStaffs;

private javax.swing.JButton jButtonSystemSetting;
    private javax.swing.JButton jButtonReports;

private javax.swing.JLabel jLabelLogo;

private javax.swing.JLabel jLabelMainTitle;

private javax.swing.JPanel jPanelMain;

private javax.swing.JPanel jPanelSidebar;
// End of variables declaration
}
