/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pratikjungsinghthakuri
 */
public class DiscountOffers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DiscountOffers.class.getName());

    /**
     * Creates new form DiscountOffers
     */
    public DiscountOffers() {
        initComponents();
        new controller.DiscountController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblNavDashboard = new javax.swing.JLabel();
        lblNavRooms = new javax.swing.JLabel();
        lblNavDiscount = new javax.swing.JLabel();
        lblNavStaffs = new javax.swing.JLabel();
        lblNavSettings = new javax.swing.JLabel();
        lblNavReports = new javax.swing.JLabel();
        lblNavLogout = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        panelProfile = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        tableCardPanel = new javax.swing.JPanel();
        controlBarPanel = new javax.swing.JPanel();
        btnOngoing = new javax.swing.JButton();
        btnAddDeal = new javax.swing.JButton();
        scrollPaneTable = new javax.swing.JScrollPane();
        tblDeals = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management System - Discount & Offers");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        panelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        panelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(26, 115, 232));
        lblLogo.setText("❖  HMS");
        panelSidebar.add(lblLogo);
        lblLogo.setBounds(20, 25, 160, 35);

        lblNavDashboard.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNavDashboard.setForeground(new java.awt.Color(96, 96, 96));
        lblNavDashboard.setText("⌂   Dashboard");
        lblNavDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelSidebar.add(lblNavDashboard);
        lblNavDashboard.setBounds(15, 80, 170, 35);

        lblNavRooms.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNavRooms.setForeground(new java.awt.Color(96, 96, 96));
        lblNavRooms.setText("🚪   Rooms");
        lblNavRooms.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelSidebar.add(lblNavRooms);
        lblNavRooms.setBounds(15, 125, 170, 35);

        lblNavDiscount.setBackground(new java.awt.Color(232, 240, 254));
        lblNavDiscount.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNavDiscount.setForeground(new java.awt.Color(26, 115, 232));
        lblNavDiscount.setText("🏷   Discount & Offers");
        lblNavDiscount.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        lblNavDiscount.setOpaque(true);
        panelSidebar.add(lblNavDiscount);
        lblNavDiscount.setBounds(15, 170, 170, 35);

        lblNavStaffs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNavStaffs.setForeground(new java.awt.Color(96, 96, 96));
        lblNavStaffs.setText("👥   Staffs");
        lblNavStaffs.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelSidebar.add(lblNavStaffs);
        lblNavStaffs.setBounds(20, 250, 170, 35);

        lblNavSettings.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNavSettings.setForeground(new java.awt.Color(96, 96, 96));
        lblNavSettings.setText("⚙   System Setting");
        lblNavSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelSidebar.add(lblNavSettings);
        lblNavSettings.setBounds(10, 310, 170, 35);

        lblNavReports.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNavReports.setForeground(new java.awt.Color(96, 96, 96));
        lblNavReports.setText("📊   Reports");
        lblNavReports.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelSidebar.add(lblNavReports);
        lblNavReports.setBounds(20, 370, 170, 35);

        lblNavLogout.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNavLogout.setForeground(new java.awt.Color(96, 96, 96));
        lblNavLogout.setText("⎋   Logout");
        lblNavLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelSidebar.add(lblNavLogout);
        lblNavLogout.setBounds(20, 430, 170, 35);

        getContentPane().add(panelSidebar);
        panelSidebar.setBounds(0, 0, 220, 500);

        panelContent.setBackground(new java.awt.Color(250, 250, 250));
        panelContent.setLayout(null);

        headerPanel.setBackground(new java.awt.Color(235, 236, 239));
        headerPanel.setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(32, 33, 36));
        lblPageTitle.setText("Discount & Offers");
        headerPanel.add(lblPageTitle);
        lblPageTitle.setBounds(10, 10, 200, 30);

        panelProfile.setOpaque(false);
        panelProfile.setLayout(null);

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRole.setForeground(new java.awt.Color(32, 33, 36));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Manager");
        panelProfile.add(lblRole);
        lblRole.setBounds(10, 10, 90, 20);

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/user (1).png"))); // NOI18N
        panelProfile.add(lblUserIcon);
        lblUserIcon.setBounds(110, 0, 40, 40);

        headerPanel.add(panelProfile);
        panelProfile.setBounds(380, 5, 160, 40);

        panelContent.add(headerPanel);
        headerPanel.setBounds(20, 20, 560, 50);

        tableCardPanel.setBackground(new java.awt.Color(224, 226, 230));
        tableCardPanel.setLayout(null);

        controlBarPanel.setBackground(new java.awt.Color(255, 255, 255));
        controlBarPanel.setLayout(null);

        btnOngoing.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnOngoing.setForeground(new java.awt.Color(26, 115, 232));
        btnOngoing.setText("Ongoing");
        btnOngoing.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnOngoing.setContentAreaFilled(false);
        btnOngoing.setOpaque(true);
        controlBarPanel.add(btnOngoing);
        btnOngoing.setBounds(15, 7, 90, 30);

        btnAddDeal.setBackground(new java.awt.Color(26, 115, 232));
        btnAddDeal.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAddDeal.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDeal.setText("Add deal");
        btnAddDeal.setBorderPainted(false);
        controlBarPanel.add(btnAddDeal);
        btnAddDeal.setBounds(425, 7, 90, 30);

        tableCardPanel.add(controlBarPanel);
        controlBarPanel.setBounds(15, 15, 530, 45);

        tblDeals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Deal code", "Deal name", "Reservations left", "End date", "Status", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDeals.setGridColor(new java.awt.Color(224, 224, 224));
        tblDeals.setRowHeight(35);
        tblDeals.setShowGrid(true);
        scrollPaneTable.setViewportView(tblDeals);

        tableCardPanel.add(scrollPaneTable);
        scrollPaneTable.setBounds(0, 80, 560, 170);

        panelContent.add(tableCardPanel);
        tableCardPanel.setBounds(20, 85, 570, 400);

        getContentPane().add(panelContent);
        panelContent.setBounds(200, 0, 600, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DiscountOffers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDeal;
    private javax.swing.JButton btnOngoing;
    private javax.swing.JPanel controlBarPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNavDashboard;
    private javax.swing.JLabel lblNavDiscount;
    private javax.swing.JLabel lblNavLogout;
    private javax.swing.JLabel lblNavReports;
    private javax.swing.JLabel lblNavRooms;
    private javax.swing.JLabel lblNavSettings;
    private javax.swing.JLabel lblNavStaffs;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JPanel tableCardPanel;
    private javax.swing.JTable tblDeals;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnAddDeal() {
        return btnAddDeal;
    }

    public javax.swing.JButton getBtnOngoing() {
        return btnOngoing;
    }

    public javax.swing.JTable getTblDeals() {
        return tblDeals;
    }

    public javax.swing.JLabel getLblNavDashboard() {
        return lblNavDashboard;
    }

    public javax.swing.JLabel getLblNavRooms() {
        return lblNavRooms;
    }

    public javax.swing.JLabel getLblNavDiscount() {
        return lblNavDiscount;
    }

    public javax.swing.JLabel getLblNavStaffs() {
        return lblNavStaffs;
    }

    public javax.swing.JLabel getLblNavSettings() {
        return lblNavSettings;
    }

    public javax.swing.JLabel getLblNavReports() {
        return lblNavReports;
    }

    public javax.swing.JLabel getLblNavLogout() {
        return lblNavLogout;
    }
}
