/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author i3
 */
public class FrontdeskDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrontdeskDashboard.class.getName());

    /**
     * Creates new form FrontDashboard
     */
    public FrontdeskDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Guest = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        Mealtime = new javax.swing.JButton();
        Billing = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanelHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(810, 535));
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(37, 99, 235));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HMS");
        jPanelSidebar.add(lblLogo);
        lblLogo.setBounds(10, 30, 140, 30);

        Dashboard.setBackground(new java.awt.Color(211, 228, 245));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(37, 99, 235));
        Dashboard.setText("  Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setFocusPainted(false);
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard.addActionListener(this::DashboardActionPerformed);
        jPanelSidebar.add(Dashboard);
        Dashboard.setBounds(10, 80, 160, 35);

        Guest.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Guest.setText(" Guest");
        Guest.setBorderPainted(false);
        Guest.setContentAreaFilled(false);
        Guest.setFocusPainted(false);
        Guest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Guest.addActionListener(this::GuestActionPerformed);
        jPanelSidebar.add(Guest);
        Guest.setBounds(10, 120, 160, 35);

        Booking.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Booking.setText(" Booking");
        Booking.setBorderPainted(false);
        Booking.setContentAreaFilled(false);
        Booking.setFocusPainted(false);
        Booking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Booking.addActionListener(this::BookingActionPerformed);
        jPanelSidebar.add(Booking);
        Booking.setBounds(10, 160, 160, 35);

        Mealtime.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Mealtime.setText(" Mealtime");
        Mealtime.setBorderPainted(false);
        Mealtime.setContentAreaFilled(false);
        Mealtime.setFocusPainted(false);
        Mealtime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mealtime.addActionListener(this::MealtimeActionPerformed);
        jPanelSidebar.add(Mealtime);
        Mealtime.setBounds(10, 200, 160, 35);

        Billing.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Billing.setText(" Billing");
        Billing.setBorderPainted(false);
        Billing.setContentAreaFilled(false);
        Billing.setFocusPainted(false);
        Billing.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Billing.addActionListener(this::BillingActionPerformed);
        jPanelSidebar.add(Billing);
        Billing.setBounds(10, 240, 160, 35);

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Logout.setText(" Logout");
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setFocusPainted(false);
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.addActionListener(this::LogoutActionPerformed);
        jPanelSidebar.add(Logout);
        Logout.setBounds(10, 280, 160, 35);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 180, 500);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(0, 0, 10, 500);

        jPanelHeader.setBackground(new java.awt.Color(211, 228, 245));
        jPanelHeader.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(64, 64, 64));
        lblTitle.setText("Frontdesk Dashboard");
        jPanelHeader.add(lblTitle);
        lblTitle.setBounds(10, 5, 180, 30);

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(64, 64, 64));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Frontdesk");
        jPanelHeader.add(lblRole);
        lblRole.setBounds(420, 5, 100, 30);

        jPanel1.add(jPanelHeader);
        jPanelHeader.setBounds(20, 15, 580, 40);

        jPanel2.setBackground(new java.awt.Color(211, 228, 245));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setText("Overview");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 16);

        jLabel2.setText("Total");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(380, 40, 50, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Available rooms");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(380, 60, 100, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 99, 235));
        jLabel4.setText("20");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(490, 50, 40, 30);

        jLabel5.setText("Total");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 40, 50, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Rooms");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 60, 60, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 99, 235));
        jLabel7.setText("51");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(70, 50, 40, 30);

        jLabel8.setText("Total");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(190, 40, 50, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Occupied rooms");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(190, 60, 100, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 99, 235));
        jLabel10.setText("31");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(300, 50, 40, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 550, 90);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Available Rooms");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(220, 110, 100, 20);

        jPanel4.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 110, 20, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Booked Rooms");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(50, 110, 100, 20);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(190, 110, 20, 20);

        jPanel6.setBackground(new java.awt.Color(114, 173, 218));
        jPanel6.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(0, 255, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("117");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 170, 35, 30);

        jLabel14.setBackground(new java.awt.Color(0, 255, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("101");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 10, 35, 30);

        jLabel15.setBackground(new java.awt.Color(0, 255, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setText("102");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        jPanel6.add(jLabel15);
        jLabel15.setBounds(60, 10, 35, 30);

        jLabel16.setBackground(new java.awt.Color(0, 255, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setText("103");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);
        jPanel6.add(jLabel16);
        jLabel16.setBounds(110, 10, 35, 30);

        jLabel18.setBackground(new java.awt.Color(0, 255, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setText("107");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setOpaque(true);
        jPanel6.add(jLabel18);
        jLabel18.setBounds(110, 50, 35, 30);

        jLabel19.setBackground(new java.awt.Color(0, 255, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setText("105");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);
        jPanel6.add(jLabel19);
        jLabel19.setBounds(10, 50, 35, 30);

        jLabel21.setBackground(new java.awt.Color(0, 255, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setText("112");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setOpaque(true);
        jPanel6.add(jLabel21);
        jLabel21.setBounds(160, 90, 35, 30);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setText("116");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setOpaque(true);
        jPanel6.add(jLabel22);
        jLabel22.setBounds(160, 130, 35, 30);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel23.setText("106");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.setOpaque(true);
        jPanel6.add(jLabel23);
        jLabel23.setBounds(60, 50, 35, 30);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel24.setText("109");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setOpaque(true);
        jPanel6.add(jLabel24);
        jLabel24.setBounds(10, 90, 35, 30);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel25.setText("111");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel25.setOpaque(true);
        jPanel6.add(jLabel25);
        jLabel25.setBounds(110, 90, 35, 30);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel26.setText("115");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel26.setOpaque(true);
        jPanel6.add(jLabel26);
        jLabel26.setBounds(110, 130, 35, 30);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel27.setText("119");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel27.setOpaque(true);
        jPanel6.add(jLabel27);
        jLabel27.setBounds(110, 170, 35, 30);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel28.setText("113");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setOpaque(true);
        jPanel6.add(jLabel28);
        jLabel28.setBounds(10, 130, 35, 30);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel29.setText("110");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.setOpaque(true);
        jPanel6.add(jLabel29);
        jLabel29.setBounds(60, 90, 35, 30);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel30.setText("122");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.setOpaque(true);
        jPanel6.add(jLabel30);
        jLabel30.setBounds(60, 210, 35, 30);

        jLabel31.setBackground(new java.awt.Color(0, 255, 0));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel31.setText("121");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.setOpaque(true);
        jPanel6.add(jLabel31);
        jLabel31.setBounds(10, 210, 35, 30);

        jLabel32.setBackground(new java.awt.Color(0, 255, 0));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel32.setText("118");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.setOpaque(true);
        jPanel6.add(jLabel32);
        jLabel32.setBounds(60, 170, 35, 30);

        jLabel33.setBackground(new java.awt.Color(0, 255, 0));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel33.setText("114");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.setOpaque(true);
        jPanel6.add(jLabel33);
        jLabel33.setBounds(60, 130, 35, 30);

        jLabel34.setBackground(new java.awt.Color(0, 255, 0));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel34.setText("124");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.setOpaque(true);
        jPanel6.add(jLabel34);
        jLabel34.setBounds(160, 210, 35, 30);

        jLabel35.setBackground(new java.awt.Color(0, 255, 0));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel35.setText("120");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.setOpaque(true);
        jPanel6.add(jLabel35);
        jLabel35.setBounds(160, 170, 35, 30);

        jLabel36.setBackground(new java.awt.Color(0, 255, 0));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel36.setText("123");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.setOpaque(true);
        jPanel6.add(jLabel36);
        jLabel36.setBounds(110, 210, 35, 30);

        jLabel37.setBackground(new java.awt.Color(0, 255, 0));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel37.setText("104");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.setOpaque(true);
        jPanel6.add(jLabel37);
        jLabel37.setBounds(160, 10, 35, 30);

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel45.setText("108");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel45.setOpaque(true);
        jPanel6.add(jLabel45);
        jLabel45.setBounds(160, 50, 35, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 160, 210, 250);

        jPanel7.setBackground(new java.awt.Color(154, 104, 204));
        jPanel7.setLayout(null);

        jLabel17.setBackground(new java.awt.Color(0, 255, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel17.setText("210");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setOpaque(true);
        jPanel7.add(jLabel17);
        jLabel17.setBounds(10, 130, 35, 30);

        jLabel38.setBackground(new java.awt.Color(0, 255, 0));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel38.setText("201");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel38.setOpaque(true);
        jPanel7.add(jLabel38);
        jLabel38.setBounds(10, 10, 35, 30);

        jLabel39.setBackground(new java.awt.Color(0, 255, 0));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel39.setText("202");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel39.setOpaque(true);
        jPanel7.add(jLabel39);
        jLabel39.setBounds(60, 10, 35, 30);

        jLabel41.setBackground(new java.awt.Color(0, 255, 0));
        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel41.setText("209");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.setOpaque(true);
        jPanel7.add(jLabel41);
        jLabel41.setBounds(110, 90, 35, 30);

        jLabel42.setBackground(new java.awt.Color(0, 255, 0));
        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel42.setText("205");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel42.setOpaque(true);
        jPanel7.add(jLabel42);
        jLabel42.setBounds(60, 50, 35, 30);

        jLabel43.setBackground(new java.awt.Color(0, 255, 0));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel43.setText("204");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel43.setOpaque(true);
        jPanel7.add(jLabel43);
        jLabel43.setBounds(10, 50, 35, 30);

        jLabel44.setBackground(new java.awt.Color(0, 255, 0));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel44.setText("104");
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel44.setOpaque(true);
        jPanel7.add(jLabel44);
        jLabel44.setBounds(10, 130, 35, 30);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setText("212");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setOpaque(true);
        jPanel7.add(jLabel20);
        jLabel20.setBounds(110, 130, 35, 30);

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel46.setText("207");
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel46.setOpaque(true);
        jPanel7.add(jLabel46);
        jLabel46.setBounds(10, 90, 35, 30);

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel48.setText("211");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel48.setOpaque(true);
        jPanel7.add(jLabel48);
        jLabel48.setBounds(60, 130, 35, 30);

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel49.setText("213");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel49.setOpaque(true);
        jPanel7.add(jLabel49);
        jLabel49.setBounds(10, 170, 35, 30);

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel50.setText("216");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel50.setOpaque(true);
        jPanel7.add(jLabel50);
        jLabel50.setBounds(10, 210, 35, 30);

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel51.setText("217");
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel51.setOpaque(true);
        jPanel7.add(jLabel51);
        jLabel51.setBounds(60, 210, 35, 30);

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel52.setText("215");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel52.setOpaque(true);
        jPanel7.add(jLabel52);
        jLabel52.setBounds(110, 170, 35, 30);

        jLabel53.setBackground(new java.awt.Color(0, 255, 0));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel53.setText("104");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel53.setOpaque(true);
        jPanel7.add(jLabel53);
        jLabel53.setBounds(110, 90, 35, 30);

        jLabel54.setBackground(new java.awt.Color(0, 255, 0));
        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel54.setText("206");
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel54.setOpaque(true);
        jPanel7.add(jLabel54);
        jLabel54.setBounds(110, 50, 35, 30);

        jLabel55.setBackground(new java.awt.Color(0, 255, 0));
        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel55.setText("104");
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel55.setOpaque(true);
        jPanel7.add(jLabel55);
        jLabel55.setBounds(110, 50, 35, 30);

        jLabel56.setBackground(new java.awt.Color(0, 255, 0));
        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel56.setText("214");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel56.setOpaque(true);
        jPanel7.add(jLabel56);
        jLabel56.setBounds(60, 170, 35, 30);

        jLabel57.setBackground(new java.awt.Color(0, 255, 0));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel57.setText("104");
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel57.setOpaque(true);
        jPanel7.add(jLabel57);
        jLabel57.setBounds(60, 170, 35, 30);

        jLabel58.setBackground(new java.awt.Color(0, 255, 0));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel58.setText("218");
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel58.setOpaque(true);
        jPanel7.add(jLabel58);
        jLabel58.setBounds(110, 210, 35, 30);

        jLabel59.setBackground(new java.awt.Color(0, 255, 0));
        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel59.setText("104");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel59.setOpaque(true);
        jPanel7.add(jLabel59);
        jLabel59.setBounds(110, 210, 35, 30);

        jLabel61.setBackground(new java.awt.Color(0, 255, 0));
        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel61.setText("203");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel61.setOpaque(true);
        jPanel7.add(jLabel61);
        jLabel61.setBounds(110, 10, 35, 30);

        jLabel66.setBackground(new java.awt.Color(255, 255, 255));
        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel66.setText("208");
        jLabel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel66.setOpaque(true);
        jPanel7.add(jLabel66);
        jLabel66.setBounds(60, 90, 35, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(230, 160, 160, 250);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(null);

        jLabel60.setBackground(new java.awt.Color(0, 255, 0));
        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel60.setText("304");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel60.setOpaque(true);
        jPanel8.add(jLabel60);
        jLabel60.setBounds(10, 50, 35, 30);

        jLabel62.setBackground(new java.awt.Color(0, 255, 0));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel62.setText("306");
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel62.setOpaque(true);
        jPanel8.add(jLabel62);
        jLabel62.setBounds(110, 50, 35, 30);

        jLabel63.setBackground(new java.awt.Color(0, 255, 0));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel63.setText("301");
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel63.setOpaque(true);
        jPanel8.add(jLabel63);
        jLabel63.setBounds(10, 10, 35, 30);

        jLabel64.setBackground(new java.awt.Color(0, 255, 0));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel64.setText("308");
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel64.setOpaque(true);
        jPanel8.add(jLabel64);
        jLabel64.setBounds(60, 90, 35, 30);

        jLabel65.setBackground(new java.awt.Color(0, 255, 0));
        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel65.setText("302");
        jLabel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel65.setOpaque(true);
        jPanel8.add(jLabel65);
        jLabel65.setBounds(60, 10, 35, 30);

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel47.setText("309");
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel47.setOpaque(true);
        jPanel8.add(jLabel47);
        jLabel47.setBounds(110, 90, 35, 30);

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel67.setText("303");
        jLabel67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel67.setOpaque(true);
        jPanel8.add(jLabel67);
        jLabel67.setBounds(110, 10, 35, 30);

        jLabel68.setBackground(new java.awt.Color(255, 255, 255));
        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel68.setText("305");
        jLabel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel68.setOpaque(true);
        jPanel8.add(jLabel68);
        jLabel68.setBounds(60, 50, 35, 30);

        jLabel70.setBackground(new java.awt.Color(255, 255, 255));
        jLabel70.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel70.setText("108");
        jLabel70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel70.setOpaque(true);
        jPanel8.add(jLabel70);
        jLabel70.setBounds(110, 90, 35, 30);

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel71.setText("307");
        jLabel71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel71.setOpaque(true);
        jPanel8.add(jLabel71);
        jLabel71.setBounds(10, 90, 35, 30);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(410, 160, 150, 130);

        jLabel40.setBackground(new java.awt.Color(24, 131, 213));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(15, 15, 178));
        jLabel40.setText("VIP Rooms");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(440, 140, 110, 20);

        jLabel74.setBackground(new java.awt.Color(24, 131, 213));
        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(24, 131, 213));
        jLabel74.setText("Single Bedrooms");
        jPanel2.add(jLabel74);
        jLabel74.setBounds(70, 140, 120, 20);

        jLabel75.setBackground(new java.awt.Color(24, 131, 213));
        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(121, 23, 218));
        jLabel75.setText("Double Bedrooms");
        jPanel2.add(jLabel75);
        jLabel75.setBounds(260, 140, 130, 20);
        jPanel2.add(jCalendar1);
        jCalendar1.setBounds(400, 300, 170, 120);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 70, 580, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 0, 620, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillingActionPerformed

    private void MealtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealtimeActionPerformed

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingActionPerformed

    private void GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestActionPerformed

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrontdeskDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Billing;
    private javax.swing.JButton Booking;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Guest;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Mealtime;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
