/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class gest_dashbord extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gest_dashbord.class.getName());

    /**
     * Creates new form gest_dashbord
     */
    public gest_dashbord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setText("Book Room");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 117, 121, 32);

        jButton3.setText("Order Food");
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 167, 121, 32);

        jButton4.setText("Feedback");
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 217, 121, 32);

        jButton6.setText("Logout");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 267, 121, 32);

        jLabel2.setText("           HMS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 15, 121, 34);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("YOUR CURRENT STAY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 117, 145, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Welcome");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(199, 78, 145, 32);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("HOTEL AMENITIES");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 300, 145, 32);

        jLabel1.setText("Infinity Pool");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 341, 90, 26);

        jLabel3.setText("Fitness Center");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 379, 90, 26);

        jLabel4.setText("The Zen Spa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 417, 90, 26);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Order Food ");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5);
        jButton5.setBounds(570, 120, 158, 23);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gourmet dining delivered ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(580, 140, 140, 24);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Room Service");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        getContentPane().add(jButton7);
        jButton7.setBounds(550, 210, 198, 23);

        jLabel12.setText("Housekeeping, towels or ammenities ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(550, 240, 198, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 255));
        jLabel11.setText("View Expenses");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(448, 390, 99, 26);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("$ 3000");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(454, 422, 83, 32);

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Room");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(220, 177, 68, 16);

        jLabel15.setText("  VIP");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 155, 68, 16);

        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("CHECK-IN");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 234, 86, 16);

        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("CHECK-OUT");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(334, 234, 86, 16);

        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("GUESTS");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(432, 234, 86, 16);

        jButton8.setBackground(new java.awt.Color(81, 72, 242));
        jButton8.setText("Dashboard");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 70, 120, 30);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(0, 0, 170, 500);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("  Dashboard Overview");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(190, 20, 177, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Guest");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(680, 20, 50, 20);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 10, 610, 40);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(541, 192, 220, 80);

        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(540, 102, 220, 80);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(190, 70, 590, 390);

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 60, 610, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gest_dashbord().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
