package view;

/**
 * Guest Details View Frame
 * Managed programmatically to match mockup UI.
 */
public class Gust_Details extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gust_Details.class.getName());

    private String roomType;

    /**
     * Creates new form Gust_Details
     */
    public Gust_Details() {
        initComponents();
    }

    public String getRoomType() {
        return roomType;
    }

    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnRooms = new javax.swing.JButton();
        btnDiscounts = new javax.swing.JButton();
        btnStaffs = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnSystemSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Booking");
        setMinimumSize(new java.awt.Dimension(800, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(219, 234, 254));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 24, 36));
        jLabel4.setText("  Guest Details");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 0, 220, 35);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 114, 128));
        jLabel5.setText("Please provide the primary guest information for this reservation.");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 30, 460, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 85, 99));
        jLabel6.setText("FULL NAME");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 60, 220, 20);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(40, 80, 220, 35);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 85, 99));
        jLabel7.setText("PHONE NUMBER");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(280, 60, 220, 20);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(280, 80, 220, 35);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(75, 85, 99));
        jLabel8.setText("EMAIL ADDRESS");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 130, 460, 20);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(40, 150, 460, 35);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(75, 85, 99));
        jLabel13.setText("HOME ADDRESS");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 190, 460, 20);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(40, 210, 460, 35);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(75, 85, 99));
        jLabel11.setText("CHECK-IN DATE");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 260, 220, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(75, 85, 99));
        jLabel12.setText("CHECK-OUT DATE");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(290, 260, 220, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(75, 85, 99));
        jLabel10.setText("DISCOUNT DEAL");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 320, 220, 20);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(40, 340, 220, 35);

        jButton6.setBackground(new java.awt.Color(37, 99, 235));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CONFIRM BOOKING");
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jPanel3.add(jButton6);
        jButton6.setBounds(290, 340, 210, 30);
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(40, 280, 200, 30);
        jPanel3.add(jDateChooser2);
        jDateChooser2.setBounds(290, 280, 210, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 10, 540, 390);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(20, 75, 580, 420);

        jPanel4.setBackground(new java.awt.Color(219, 234, 254));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 85, 99));
        jLabel2.setText("Room Browsing");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(15, 7, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 85, 99));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Guest");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(460, 7, 70, 30);

        jPanel6.add(jPanel4);
        jPanel4.setBounds(20, 15, 580, 45);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 3, 500);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(180, 0, 620, 500);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(37, 99, 235));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HMS");
        jPanelSidebar.add(lblLogo);
        lblLogo.setBounds(10, 30, 140, 30);

        btnRooms.setBackground(new java.awt.Color(211, 228, 245));
        btnRooms.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnRooms.setForeground(new java.awt.Color(37, 99, 235));
        btnRooms.setText("  Room Browsing");
        btnRooms.setBorderPainted(false);
        btnRooms.setFocusPainted(false);
        btnRooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRooms.addActionListener(this::btnRoomsActionPerformed);
        jPanelSidebar.add(btnRooms);
        btnRooms.setBounds(10, 120, 160, 35);

        btnDiscounts.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDiscounts.setText("  Order Food");
        btnDiscounts.setBorderPainted(false);
        btnDiscounts.setContentAreaFilled(false);
        btnDiscounts.setFocusPainted(false);
        btnDiscounts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDiscounts.addActionListener(this::btnDiscountsActionPerformed);
        jPanelSidebar.add(btnDiscounts);
        btnDiscounts.setBounds(10, 160, 160, 35);

        btnStaffs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnStaffs.setText("  Feedback");
        btnStaffs.setBorderPainted(false);
        btnStaffs.setContentAreaFilled(false);
        btnStaffs.setFocusPainted(false);
        btnStaffs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStaffs.addActionListener(this::btnStaffsActionPerformed);
        jPanelSidebar.add(btnStaffs);
        btnStaffs.setBounds(10, 200, 160, 35);

        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnReports.setText("  Logout");
        btnReports.setBorderPainted(false);
        btnReports.setContentAreaFilled(false);
        btnReports.setFocusPainted(false);
        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReports.addActionListener(this::btnReportsActionPerformed);
        jPanelSidebar.add(btnReports);
        btnReports.setBounds(10, 240, 160, 35);

        btnSystemSetting.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSystemSetting.setText("  Dashboard");
        btnSystemSetting.setBorderPainted(false);
        btnSystemSetting.setContentAreaFilled(false);
        btnSystemSetting.setFocusPainted(false);
        btnSystemSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSystemSetting.addActionListener(this::btnSystemSettingActionPerformed);
        jPanelSidebar.add(btnSystemSetting);
        btnSystemSetting.setBounds(10, 80, 160, 35);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 180, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        // Handled by Controller
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountsActionPerformed
        // Handled in other navigation sections
    }//GEN-LAST:event_btnDiscountsActionPerformed

    private void btnStaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffsActionPerformed
        // Handled by Controller
    }//GEN-LAST:event_btnStaffsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // Handled in other navigation sections
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnSystemSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSystemSettingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscounts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnStaffs;
    private javax.swing.JButton btnSystemSetting;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnDashboard() { return jButton1; }
    public javax.swing.JButton getBtnRoomBrowsing() { return jButton2; }
    public javax.swing.JButton getBtnOrderFood() { return jButton3; }
    public javax.swing.JButton getBtnFeedback() { return jButton4; }
    public javax.swing.JButton getBtnLogout() { return jButton5; }
    public javax.swing.JButton getBtnConfirmBooking() { return jButton6; }

    public javax.swing.JTextField getTxtFullName() { return jTextField1; }
    public javax.swing.JTextField getTxtPhoneNumber() { return jTextField6; }
    public javax.swing.JTextField getTxtEmailAddress() { return jTextField4; }
    public javax.swing.JTextField getTxtHomeAddress() { return jTextField7; }
    public javax.swing.JTextField getTxtDiscountDeal() { return jTextField8; }

    public com.toedter.calendar.JDateChooser getDateChooserCheckIn() { return dateChooserCheckIn; }
    public com.toedter.calendar.JDateChooser getDateChooserCheckOut() { return dateChooserCheckOut; }
}
