/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ADMIN
 */
public class MealTime extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MealTime.class.getName());

    /**
     * Creates new form MealTime
     */
    public MealTime() {
        initComponents();
        new controller.MealTimeController(this).loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSidebar = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonRooms = new javax.swing.JButton();
        jButtonBookings = new javax.swing.JButton();
        jButtonMealTime = new javax.swing.JButton();
        jButtonBilling = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelHeaderTitle = new javax.swing.JLabel();
        jLabelHeaderUser = new javax.swing.JLabel();
        jPanelCard = new javax.swing.JPanel();
        jButtonEdit = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jButtonEdit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meal Time Management");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(0, 92, 255));
        jLabelLogo.setText("HMS");
        jPanelSidebar.add(jLabelLogo);
        jLabelLogo.setBounds(25, 30, 170, 40);

        jButtonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDashboard.setForeground(new java.awt.Color(43, 74, 105));
        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.setBorderPainted(false);
        jButtonDashboard.setContentAreaFilled(false);
        jButtonDashboard.setFocusPainted(false);
        jButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDashboard.addActionListener(this::jButtonDashboardActionPerformed);
        jPanelSidebar.add(jButtonDashboard);
        jButtonDashboard.setBounds(20, 100, 180, 40);

        jButtonRooms.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRooms.setForeground(new java.awt.Color(43, 74, 105));
        jButtonRooms.setText("Rooms");
        jButtonRooms.setBorderPainted(false);
        jButtonRooms.setContentAreaFilled(false);
        jButtonRooms.setFocusPainted(false);
        jButtonRooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRooms.addActionListener(this::jButtonRoomsActionPerformed);
        jPanelSidebar.add(jButtonRooms);
        jButtonRooms.setBounds(20, 150, 180, 40);

        jButtonBookings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBookings.setForeground(new java.awt.Color(43, 74, 105));
        jButtonBookings.setText("Bookings");
        jButtonBookings.setBorderPainted(false);
        jButtonBookings.setContentAreaFilled(false);
        jButtonBookings.setFocusPainted(false);
        jButtonBookings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBookings.addActionListener(this::jButtonBookingsActionPerformed);
        jPanelSidebar.add(jButtonBookings);
        jButtonBookings.setBounds(20, 200, 180, 40);

        jButtonMealTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMealTime.setForeground(new java.awt.Color(0, 92, 255));
        jButtonMealTime.setBackground(new java.awt.Color(235, 243, 254));
        jButtonMealTime.setText("Meal Time");
        jButtonMealTime.setBorderPainted(false);
        jButtonMealTime.setFocusPainted(false);
        jButtonMealTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanelSidebar.add(jButtonMealTime);
        jButtonMealTime.setBounds(20, 250, 180, 40);

        jButtonBilling.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBilling.setForeground(new java.awt.Color(43, 74, 105));
        jButtonBilling.setText("Billing");
        jButtonBilling.setBorderPainted(false);
        jButtonBilling.setContentAreaFilled(false);
        jButtonBilling.setFocusPainted(false);
        jButtonBilling.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBilling.addActionListener(this::jButtonBillingActionPerformed);
        jPanelSidebar.add(jButtonBilling);
        jButtonBilling.setBounds(20, 300, 180, 40);

        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(43, 74, 105));
        jButtonLogout.setText("Logout");
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);
        jPanelSidebar.add(jButtonLogout);
        jButtonLogout.setBounds(20, 340, 180, 40);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 220, 610);

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setLayout(null);

        jPanelHeader.setBackground(new java.awt.Color(220, 228, 236));
        jPanelHeader.setLayout(null);

        jLabelHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelHeaderTitle.setForeground(new java.awt.Color(51, 51, 51));
        jLabelHeaderTitle.setText("Meal Time Management");
        jPanelHeader.add(jLabelHeaderTitle);
        jLabelHeaderTitle.setBounds(20, 12, 300, 30);

        jLabelHeaderUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHeaderUser.setForeground(new java.awt.Color(43, 74, 105));
        jLabelHeaderUser.setText("Frontdesk  👤");
        jLabelHeaderUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelHeader.add(jLabelHeaderUser);
        jLabelHeaderUser.setBounds(420, 12, 180, 30);

        jPanelContent.add(jPanelHeader);
        jPanelHeader.setBounds(30, 20, 620, 55);

        jPanelCard.setBackground(new java.awt.Color(224, 224, 224));
        jPanelCard.setLayout(null);

        jButtonEdit.setBackground(new java.awt.Color(0, 92, 255));
        jButtonEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("SAVE");
        jButtonEdit.setFocusPainted(false);
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);
        jPanelCard.add(jButtonEdit);
        jButtonEdit.setBounds(500, 300, 100, 36);

        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ROOM TYPE", "BREAKFAST TIMING", "LUNCH TIMING", "DINNER TIMING"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSchedule.setRowHeight(40);
        jTableSchedule.setShowGrid(true);
        jScrollPaneTable.setViewportView(jTableSchedule);

        jPanelCard.add(jScrollPaneTable);
        jScrollPaneTable.setBounds(20, 80, 580, 170);

        jButtonEdit1.setBackground(new java.awt.Color(0, 92, 255));
        jButtonEdit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEdit1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit1.setText("EDIT");
        jButtonEdit1.setFocusPainted(false);
        jPanelCard.add(jButtonEdit1);
        jButtonEdit1.setBounds(370, 300, 100, 36);

        jPanelContent.add(jPanelCard);
        jPanelCard.setBounds(30, 120, 620, 370);

        getContentPane().add(jPanelContent);
        jPanelContent.setBounds(220, 0, 680, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRoomsActionPerformed

    private void jButtonBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookingsActionPerformed

    private void jButtonBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillingActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    public javax.swing.JTable getjTableSchedule() {
        return jTableSchedule;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MealTime().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBilling;
    private javax.swing.JButton jButtonBookings;
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEdit1;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMealTime;
    private javax.swing.JButton jButtonRooms;
    private javax.swing.JLabel jLabelHeaderTitle;
    private javax.swing.JLabel jLabelHeaderUser;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTableSchedule;
    // End of variables declaration//GEN-END:variables
}
