/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ADMIN
 */
public class reports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(reports.class.getName());

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
        setupFeedbackTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        Rooms = new javax.swing.JButton();
        Discount = new javax.swing.JButton();
        Staffs = new javax.swing.JButton();
        Sysetemsettings = new javax.swing.JButton();
        Reports = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 535));
        setPreferredSize(new java.awt.Dimension(930, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSidebar.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(37, 99, 235));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HMS");
        jPanelSidebar.add(lblLogo);
        lblLogo.setBounds(10, 30, 140, 30);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(37, 99, 235));
        Dashboard.setText("  Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        Dashboard.setFocusPainted(false);
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard.addActionListener(this::DashboardActionPerformed);
        jPanelSidebar.add(Dashboard);
        Dashboard.setBounds(10, 80, 160, 35);

        Rooms.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Rooms.setText(" Rooms");
        Rooms.setBorderPainted(false);
        Rooms.setContentAreaFilled(false);
        Rooms.setFocusPainted(false);
        Rooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Rooms.addActionListener(this::RoomsActionPerformed);
        jPanelSidebar.add(Rooms);
        Rooms.setBounds(10, 120, 160, 35);

        Discount.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Discount.setText(" Discount & Offers");
        Discount.setBorderPainted(false);
        Discount.setContentAreaFilled(false);
        Discount.setFocusPainted(false);
        Discount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Discount.addActionListener(this::DiscountActionPerformed);
        jPanelSidebar.add(Discount);
        Discount.setBounds(10, 160, 160, 35);

        Staffs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Staffs.setText(" Staffs");
        Staffs.setBorderPainted(false);
        Staffs.setContentAreaFilled(false);
        Staffs.setFocusPainted(false);
        Staffs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Staffs.addActionListener(this::StaffsActionPerformed);
        jPanelSidebar.add(Staffs);
        Staffs.setBounds(10, 200, 160, 35);

        Sysetemsettings.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Sysetemsettings.setText(" System Settings");
        Sysetemsettings.setBorderPainted(false);
        Sysetemsettings.setContentAreaFilled(false);
        Sysetemsettings.setFocusPainted(false);
        Sysetemsettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sysetemsettings.addActionListener(this::SysetemsettingsActionPerformed);
        jPanelSidebar.add(Sysetemsettings);
        Sysetemsettings.setBounds(10, 240, 160, 35);

        Reports.setBackground(new java.awt.Color(211, 228, 245));
        Reports.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Reports.setForeground(new java.awt.Color(37, 99, 235));
        Reports.setText(" Reports");
        Reports.setBorderPainted(false);
        Reports.setFocusPainted(false);
        Reports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Reports.addActionListener(this::ReportsActionPerformed);
        jPanelSidebar.add(Reports);
        Reports.setBounds(10, 280, 160, 35);

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Logout.setText(" Logout");
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setFocusPainted(false);
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.addActionListener(this::LogoutActionPerformed);
        jPanelSidebar.add(Logout);
        Logout.setBounds(10, 320, 160, 35);

        getContentPane().add(jPanelSidebar);
        jPanelSidebar.setBounds(0, 0, 180, 500);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 3, 500);

        jPanelHeader.setBackground(new java.awt.Color(211, 228, 245));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 85, 99));
        jLabel2.setText("Repots");
        jPanelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, 220, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(75, 85, 99));
        jLabel25.setText("Manager");
        jPanelHeader.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jPanel4.add(jPanelHeader);
        jPanelHeader.setBounds(20, 20, 560, 37);

        jPanelContent.setBackground(new java.awt.Color(211, 228, 245));
        jPanelContent.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("00");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 60, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 85, 99));
        jLabel6.setText("Total Booking ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 10, 100, 18);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("00");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 30, 60, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 85, 99));
        jLabel7.setText("Total Booking ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 10, 100, 18);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("00");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 30, 60, 40);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(75, 85, 99));
        jLabel8.setText("Total Booking ");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 10, 100, 18);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("00");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(50, 30, 60, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(75, 85, 99));
        jLabel20.setText("Total Booking ");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 8, 100, 20);

        jPanelContent.add(jPanel1);
        jPanel1.setBounds(20, 20, 170, 80);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(75, 85, 99));
        jLabel10.setText("Staff Attendance");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(20, 10, 120, 18);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("00");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(50, 30, 60, 40);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(75, 85, 99));
        jLabel27.setText("Staff Attendance");
        jPanel14.add(jLabel27);
        jLabel27.setBounds(20, 10, 120, 18);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("00");
        jPanel14.add(jLabel28);
        jLabel28.setBounds(50, 30, 60, 40);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(75, 85, 99));
        jLabel29.setText("Total Booking ");
        jPanel15.add(jLabel29);
        jLabel29.setBounds(20, 10, 100, 18);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("00");
        jPanel15.add(jLabel30);
        jLabel30.setBounds(50, 30, 60, 40);

        jPanel14.add(jPanel15);
        jPanel15.setBounds(0, 0, 0, 0);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(75, 85, 99));
        jLabel31.setText("Total Booking ");
        jPanel16.add(jLabel31);
        jLabel31.setBounds(20, 10, 100, 18);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("00");
        jPanel16.add(jLabel32);
        jLabel32.setBounds(50, 30, 60, 40);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(75, 85, 99));
        jLabel33.setText("Total Booking ");
        jPanel17.add(jLabel33);
        jLabel33.setBounds(20, 10, 100, 18);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setText("00");
        jPanel17.add(jLabel34);
        jLabel34.setBounds(50, 30, 60, 40);

        jPanel16.add(jPanel17);
        jPanel17.setBounds(0, 0, 0, 0);

        jPanel14.add(jPanel16);
        jPanel16.setBounds(0, 0, 0, 0);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(75, 85, 99));
        jLabel35.setText("Staff Attendance");
        jPanel18.add(jLabel35);
        jLabel35.setBounds(20, 10, 120, 18);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setText("00");
        jPanel18.add(jLabel36);
        jLabel36.setBounds(50, 30, 60, 40);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(75, 85, 99));
        jLabel37.setText("Total Booking ");
        jPanel19.add(jLabel37);
        jLabel37.setBounds(20, 10, 100, 18);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setText("00");
        jPanel19.add(jLabel38);
        jLabel38.setBounds(50, 30, 60, 40);

        jPanel18.add(jPanel19);
        jPanel19.setBounds(0, 0, 0, 0);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(null);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(75, 85, 99));
        jLabel39.setText("Total Booking ");
        jPanel20.add(jLabel39);
        jLabel39.setBounds(20, 10, 100, 18);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setText("00");
        jPanel20.add(jLabel40);
        jLabel40.setBounds(50, 30, 60, 40);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(75, 85, 99));
        jLabel41.setText("Total Booking ");
        jPanel21.add(jLabel41);
        jLabel41.setBounds(20, 10, 100, 18);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setText("00");
        jPanel21.add(jLabel42);
        jLabel42.setBounds(50, 30, 60, 40);

        jPanel20.add(jPanel21);
        jPanel21.setBounds(0, 0, 0, 0);

        jPanel18.add(jPanel20);
        jPanel20.setBounds(0, 0, 0, 0);

        jPanel14.add(jPanel18);
        jPanel18.setBounds(20, 110, 170, 80);

        jPanel6.add(jPanel14);
        jPanel14.setBounds(20, 110, 170, 80);

        jPanelContent.add(jPanel6);
        jPanel6.setBounds(20, 160, 170, 80);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(75, 85, 99));
        jLabel12.setText("Total Offers");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(20, 10, 100, 18);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("00");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(50, 30, 60, 40);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(75, 85, 99));
        jLabel14.setText("Total Booking ");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(20, 10, 100, 18);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("00");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(50, 30, 60, 40);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 0, 0);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(75, 85, 99));
        jLabel16.setText("Total Booking ");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(20, 10, 100, 18);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("00");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(50, 30, 60, 40);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(75, 85, 99));
        jLabel18.setText("Total Booking ");
        jPanel10.add(jLabel18);
        jLabel18.setBounds(20, 10, 100, 18);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("00");
        jPanel10.add(jLabel19);
        jLabel19.setBounds(50, 30, 60, 40);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 0, 0, 0);

        jPanel7.add(jPanel9);
        jPanel9.setBounds(0, 0, 0, 0);

        jPanelContent.add(jPanel7);
        jPanel7.setBounds(20, 290, 170, 80);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 85, 99));
        jLabel5.setText("Feedback and Review");
        jPanel11.add(jLabel5);
        jLabel5.setBounds(80, 10, 150, 18);

        jPanelContent.add(jPanel11);
        jPanel11.setBounds(240, 20, 340, 350);

        jPanel4.add(jPanelContent);
        jPanelContent.setBounds(20, 90, 590, 390);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(180, 0, 620, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void RoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomsActionPerformed

    private void DiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscountActionPerformed

    private void StaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffsActionPerformed

    private void SysetemsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SysetemsettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SysetemsettingsActionPerformed

    private void ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new reports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Discount;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Reports;
    private javax.swing.JButton Rooms;
    private javax.swing.JButton Staffs;
    private javax.swing.JButton Sysetemsettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JTable jTableFeedback;
    private javax.swing.JScrollPane jScrollPaneFeedback;

    private void setupFeedbackTable() {
        jScrollPaneFeedback = new javax.swing.JScrollPane();
        jTableFeedback = new javax.swing.JTable();

        jTableFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Service", "Clean", "Food", "Review"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        jTableFeedback.setRowHeight(30);
        jTableFeedback.setSelectionBackground(new java.awt.Color(211, 228, 245));
        jScrollPaneFeedback.setViewportView(jTableFeedback);
        jPanel11.add(jScrollPaneFeedback);
        jScrollPaneFeedback.setBounds(10, 40, 280, 300);
    }

    public javax.swing.JLabel getLblTotalBookings() { return jLabel1; }
    public javax.swing.JLabel getLblStaffAttendance() { return jLabel11; }
    public javax.swing.JLabel getLblTotalOffers() { return jLabel13; }
    public javax.swing.JTable getTblFeedback() { return jTableFeedback; }

    public javax.swing.JButton getBtnDashboard() { return Dashboard; }
    public javax.swing.JButton getBtnRooms() { return Rooms; }
    public javax.swing.JButton getBtnDiscount() { return Discount; }
    public javax.swing.JButton getBtnStaffs() { return Staffs; }
    public javax.swing.JButton getBtnSystemSetting() { return Sysetemsettings; }
    public javax.swing.JButton getBtnReports() { return Reports; }
    public javax.swing.JButton getBtnLogout() { return Logout; }
}
