/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rikes
 */
public class roommanagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(roommanagement.class.getName());

    /**
     * Creates new form roommanagement
     */
    public roommanagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonAllRooms = new javax.swing.JButton();
        jButtonAvailableRooms = new javax.swing.JButton();
        jButtonBookedRooms = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rooms Management");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(229, 231, 235)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 99, 235));
        jLabel1.setText("    HMS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 130, 35));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(75, 85, 99));
        jButton2.setText("    Dashboard");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, 140, 32));

        jButton3.setBackground(new java.awt.Color(219, 234, 254));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(37, 99, 235));
        jButton3.setText("    Rooms");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 140, 32));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(75, 85, 99));
        jButton1.setText("    Discount & Offers");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 140, 32));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(75, 85, 99));
        jButton4.setText("    Staffs");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 140, 32));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(75, 85, 99));
        jButton5.setText("    System Setting");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 140, 32));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(75, 85, 99));
        jButton6.setText("    Reports");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, 140, 32));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(75, 85, 99));
        jButton7.setText("    Logout");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, 140, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 500));

        jPanel2.setBackground(new java.awt.Color(249, 250, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 85, 99));
        jLabel2.setText("Rooms Management");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, 220, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 85, 99));
        jLabel3.setText("Manager");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 600, 45));

        jPanel4.setBackground(new java.awt.Color(209, 213, 219));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAllRooms.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButtonAllRooms.setForeground(new java.awt.Color(37, 99, 235));
        jButtonAllRooms.setText("All room(100)");
        jButtonAllRooms.setBorderPainted(false);
        jButtonAllRooms.setContentAreaFilled(false);
        jButtonAllRooms.setFocusPainted(false);
        jPanel5.add(jButtonAllRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 105, 25));

        jButtonAvailableRooms.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButtonAvailableRooms.setForeground(new java.awt.Color(37, 99, 235));
        jButtonAvailableRooms.setText("Available room(20)");
        jButtonAvailableRooms.setBorderPainted(false);
        jButtonAvailableRooms.setContentAreaFilled(false);
        jButtonAvailableRooms.setFocusPainted(false);
        jPanel5.add(jButtonAvailableRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 15, 140, 25));

        jButtonBookedRooms.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButtonBookedRooms.setForeground(new java.awt.Color(37, 99, 235));
        jButtonBookedRooms.setText("Booked(80)");
        jButtonBookedRooms.setBorderPainted(false);
        jButtonBookedRooms.setContentAreaFilled(false);
        jButtonBookedRooms.setFocusPainted(false);
        jPanel5.add(jButtonBookedRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 100, 25));

        jButton8.setBackground(new java.awt.Color(37, 99, 235));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Add room");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 12, 90, 30));

        jTable1.setRowHeight(38);
        jTable1.setGridColor(new java.awt.Color(229, 231, 235));
        jTable1.setSelectionBackground(new java.awt.Color(239, 246, 255));
        jTable1.setSelectionForeground(new java.awt.Color(30, 64, 175));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"#001", "Double bed", "Floor - 1", "AC, shower, Double bed, towel bathtub, TV", "<html><span style='color: #2563EB; background: #DBEAFE; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Available</span></html>", "⋮"},
                {"#002", "Single bed", "Floor - 2", "AC, shower, bed, TV", "<html><span style='color: #EF4444; background: #FEE2E2; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Booked</span></html>", "⋮"},
                {"#003", "VIP", "Floor - 1", "AC, shower, Double bed, towel bathtub, TV", "<html><span style='color: #EF4444; background: #FEE2E2; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Booked</span></html>", "⋮"},
                {"#004", "VIP", "Floor - 1", "AC, shower, Double bed, towel bathtub, TV", "<html><span style='color: #10B981; background: #D1FAE5; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Reserved</span></html>", "⋮"},
                {"#005", "Single bed", "Floor - 1", "AC, shower, bed, TV", "<html><span style='color: #10B981; background: #D1FAE5; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Reserved</span></html>", "⋮"},
                {"#006", "Double bed", "Floor - 2", "AC, shower, Double bed, towel bathtub, TV", "<html><span style='color: #F59E0B; background: #FEF3C7; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Waitlist</span></html>", "⋮"},
                {"#007", "Double bed", "Floor - 3", "AC, shower, Double bed, towel bathtub, TV", "<html><span style='color: #10B981; background: #D1FAE5; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Reserved</span></html>", "⋮"},
                {"#008", "Single bed", "Floor - 5", "AC, shower, bed, TV", "<html><span style='color: #9CA3AF; background: #F3F4F6; padding: 2px 10px; border-radius: 9999px; font-weight: bold;'>Blocked</span></html>", "⋮"}
            },
            new String [] {
                "Room number", "Room type", "Room floor", "Room facility", "Status", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 540, 270));

        jButton9.setBackground(new java.awt.Color(249, 250, 251));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(75, 85, 99));
        jButton9.setText("< Previous");
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 345, 90, 25));

        jButton10.setBackground(new java.awt.Color(249, 250, 251));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(75, 85, 99));
        jButton10.setText("Next >");
        jButton10.setBorderPainted(false);
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(this::jButton10ActionPerformed);
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 345, 90, 25));

        jButton11.setText("1");
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 345, 25, 25));

        jButton12.setText("2");
        jPanel5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 345, 25, 25));

        jButton13.setText("3");
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 345, 25, 25));

        jButton14.setText("4");
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 345, 25, 25));

        jButton15.setText("5");
        jButton15.addActionListener(this::jButton15ActionPerformed);
        jPanel5.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 345, 25, 25));

        jButton16.setText("6");
        jPanel5.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 345, 25, 25));

        jButton17.setText("7");
        jPanel5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 345, 25, 25));

        jButton18.setText("8");
        jPanel5.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 345, 25, 25));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 570, 385));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, 600, 415));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 630, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new view.loginpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new view.admindashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new view.BookingManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new roommanagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAllRooms;
    private javax.swing.JButton jButtonAvailableRooms;
    private javax.swing.JButton jButtonBookedRooms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
