/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author i3
 */
public class Signup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 535));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotelpic.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(6, 6, 394, 488);

        jPanel1.setBackground(new java.awt.Color(211, 228, 245));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 40, 40);

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 70, 229));
        jLabel10.setText("👤+");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 20, 30, 30);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel11.setText("Sign up");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 20, 110, 30);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setText("Username");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 60, 320, 20);

        jTextField8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 224, 233)));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(30, 80, 320, 30);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setText("Email");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 120, 320, 20);

        jTextField7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 224, 233)));
        jTextField7.addActionListener(this::jTextField7ActionPerformed);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(30, 140, 320, 30);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setText("Phone");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 180, 320, 20);

        jTextField9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 224, 233)));
        jTextField9.addActionListener(this::jTextField9ActionPerformed);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(30, 200, 320, 30);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel15.setText("Password");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 240, 320, 20);

        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 224, 233)));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(30, 400, 320, 30);

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel16.setText("What is your primary school name?");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 380, 320, 20);

        jComboBox3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your role", "Manager", "Frontdesk Staff", "Guest" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 224, 233)));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(30, 320, 320, 30);

        jButton2.setBackground(new java.awt.Color(79, 70, 229));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign up");
        jButton2.setBorder(null);
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 440, 320, 30);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel17.setText("Security Question");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 360, 320, 20);

        jTextField10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 224, 233)));
        jPanel1.add(jTextField10);
        jTextField10.setBounds(30, 260, 320, 30);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setText("Role");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 300, 320, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 10, 380, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnSignup() { return jButton2; }
    public javax.swing.JTextField getUsernameField() { return jTextField8; }
    public javax.swing.JTextField getEmailField() { return jTextField7; }
    public javax.swing.JTextField getPhoneField() { return jTextField9; }
    public javax.swing.JTextField getPasswordField() { return jTextField10; }
    public javax.swing.JComboBox<String> getComboRole() { return jComboBox3; }
    public javax.swing.JTextField getSecurityAnswerField() { return jTextField6; }
}
